-- 1 up
--
-- PostgreSQL database dump
--


-- Dumped from database version 16.14 (Ubuntu 16.14-0ubuntu0.24.04.1)
-- Dumped by pg_dump version 16.14 (Ubuntu 16.14-0ubuntu0.24.04.1)


--
-- Name: public; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA IF NOT EXISTS public;


--
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON SCHEMA public IS 'standard public schema';


--
-- Name: minion_state; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.minion_state AS ENUM (
    'inactive',
    'active',
    'failed',
    'finished'
);


--
-- Name: position; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public."position" AS ENUM (
    'current',
    'next',
    'previous'
);


--
-- Name: minion_jobs_notify_workers(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.minion_jobs_notify_workers() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
  BEGIN
    IF new.delayed <= NOW() THEN
      NOTIFY "minion.job";
    END IF;
    RETURN NULL;
  END;
$$;


--
-- Name: minion_lock(text, integer, integer); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.minion_lock(text, integer, integer) RETURNS boolean
    LANGUAGE plpgsql
    AS $_$
DECLARE
  new_expires TIMESTAMP WITH TIME ZONE = NOW() + (INTERVAL '1 second' * $2);
BEGIN
  lock TABLE minion_locks IN exclusive mode;
  DELETE FROM minion_locks WHERE expires < NOW();
  IF (SELECT COUNT(*) >= $3 FROM minion_locks WHERE NAME = $1) THEN
    RETURN false;
  END IF;
  IF new_expires > NOW() THEN
    INSERT INTO minion_locks (name, expires) VALUES ($1, new_expires);
  END IF;
  RETURN TRUE;
END;
$_$;




--
-- Name: languages; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.languages (
    languageid integer NOT NULL,
    code character varying
);


--
-- Name: continents; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.continents (
    continentid integer NOT NULL,
    continent character varying NOT NULL,
    code character varying NOT NULL
);


--
-- Name: continents_continentid_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.continents ALTER COLUMN continentid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.continents_continentid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: countries; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.countries (
    countryid integer NOT NULL,
    cc character varying(3) NOT NULL,
    pcformat character varying,
    addressformat character varying,
    geonameid integer,
    tld character varying,
    phone character varying,
    start_of_week character varying(9) DEFAULT 'monday'::character varying NOT NULL,
    continentid integer,
    currencyid integer DEFAULT 0 NOT NULL,
    svgflag character varying
);


--
-- Name: countries_countryid_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.countries ALTER COLUMN countryid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.countries_countryid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: countrynames; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.countrynames (
    countrynameid integer NOT NULL,
    countryname character varying NOT NULL,
    languageid integer NOT NULL,
    countryid integer NOT NULL
);


--
-- Name: countrynames_countrynameid_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.countrynames ALTER COLUMN countrynameid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.countrynames_countrynameid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: currencies; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.currencies (
    currencyid integer NOT NULL,
    symbol character varying NOT NULL
);


--
-- Name: currencies_currencyid_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.currencies ALTER COLUMN currencyid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.currencies_currencyid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: currencynames; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.currencynames (
    currencynameid integer NOT NULL,
    name character varying(15) NOT NULL,
    languageid integer NOT NULL,
    currencyid integer NOT NULL,
    format character varying(31)
);


--
-- Name: currencynames_currencynameid_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.currencynames ALTER COLUMN currencynameid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.currencynames_currencynameid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: exchangerates; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.exchangerates (
    exchangerateid integer NOT NULL,
    currencyid integer NOT NULL,
    rate numeric(4,0) NOT NULL,
    ratedate timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: exchangerates_exchangerateid_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.exchangerates ALTER COLUMN exchangerateid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.exchangerates_exchangerateid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: languagenames; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.languagenames (
    languagenameid integer NOT NULL,
    languagename character varying,
    languageid integer NOT NULL,
    language integer NOT NULL
);


--
-- Name: languagenames_languagenameid_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.languagenames ALTER COLUMN languagenameid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.languagenames_languagenameid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: languages_languageid_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.languages ALTER COLUMN languageid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.languages_languageid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: languagevariants; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.languagevariants (
    languagevariantid integer NOT NULL,
    variant character varying,
    languageid integer NOT NULL
);


--
-- Name: languagevariants_languagevariantid_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.languagevariants ALTER COLUMN languagevariantid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.languagevariants_languagevariantid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: statenames; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.statenames (
    statenameid integer NOT NULL,
    statename character varying NOT NULL,
    stateid integer NOT NULL,
    languageid integer DEFAULT 1 NOT NULL
);


--
-- Name: COLUMN statenames.statename; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.statenames.statename IS 'Stat';


--
-- Name: statenames_statenameid_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.statenames ALTER COLUMN statenameid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.statenames_statenameid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: states; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.states (
    stateid integer NOT NULL,
    code character varying NOT NULL,
    countryid integer NOT NULL,
    type character varying NOT NULL,
    svgflag character varying
);


--
-- Name: states_stateid_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.states ALTER COLUMN stateid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.states_stateid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: vatrates; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.vatrates (
    vatrateid integer NOT NULL,
    rate double precision DEFAULT 0.00 NOT NULL,
    countryid integer NOT NULL
);


--
-- Name: vatrates_vatrateid_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.vatrates ALTER COLUMN vatrateid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.vatrates_vatrateid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: countries cc_uq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.countries
    ADD CONSTRAINT cc_uq UNIQUE (cc);


--
-- Name: languages code_uq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.languages
    ADD CONSTRAINT code_uq UNIQUE (code);


--
-- Name: continents continents_pk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.continents
    ADD CONSTRAINT continents_pk PRIMARY KEY (continentid);


--
-- Name: countries countries_pk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.countries
    ADD CONSTRAINT countries_pk PRIMARY KEY (countryid);


--
-- Name: countrynames countrynames_pk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.countrynames
    ADD CONSTRAINT countrynames_pk PRIMARY KEY (countrynameid);


--
-- Name: currencies currencies_pk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.currencies
    ADD CONSTRAINT currencies_pk PRIMARY KEY (currencyid);


--
-- Name: currencynames currencynames_pk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.currencynames
    ADD CONSTRAINT currencynames_pk PRIMARY KEY (currencynameid);


--
-- Name: exchangerates exchangerates_pk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.exchangerates
    ADD CONSTRAINT exchangerates_pk PRIMARY KEY (exchangerateid);


--
-- Name: languagenames languagenames_pk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.languagenames
    ADD CONSTRAINT languagenames_pk PRIMARY KEY (languagenameid);


--
-- Name: languages languages_pk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.languages
    ADD CONSTRAINT languages_pk PRIMARY KEY (languageid);


--
-- Name: languagevariants languagevariants_pk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.languagevariants
    ADD CONSTRAINT languagevariants_pk PRIMARY KEY (languagevariantid);


--
-- Name: languagenames name_uq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.languagenames
    ADD CONSTRAINT name_uq UNIQUE (languageid, language);


--
-- Name: statenames statenames_pk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.statenames
    ADD CONSTRAINT statenames_pk PRIMARY KEY (statenameid);


--
-- Name: states states_pk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.states
    ADD CONSTRAINT states_pk PRIMARY KEY (stateid);


--
-- Name: vatrates vatrates_pk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vatrates
    ADD CONSTRAINT vatrates_pk PRIMARY KEY (vatrateid);


--
-- Name: countrynames_languageid_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX countrynames_languageid_idx ON public.countrynames USING btree (languageid);


--
-- Name: languagenames_language_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX languagenames_language_idx ON public.languagenames USING btree (language);


--
-- Name: statenames_languageid_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX statenames_languageid_idx ON public.statenames USING btree (languageid) INCLUDE (languageid);


--
-- Name: states_countryid_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX states_countryid_idx ON public.states USING btree (countryid);


--
-- Name: countries continents_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.countries
    ADD CONSTRAINT continents_fk FOREIGN KEY (continentid) REFERENCES public.continents(continentid) MATCH FULL ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: countrynames countries_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.countrynames
    ADD CONSTRAINT countries_fk FOREIGN KEY (countryid) REFERENCES public.countries(countryid) MATCH FULL ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: states countries_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.states
    ADD CONSTRAINT countries_fk FOREIGN KEY (countryid) REFERENCES public.countries(countryid) MATCH FULL ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: vatrates countries_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vatrates
    ADD CONSTRAINT countries_fk FOREIGN KEY (countryid) REFERENCES public.countries(countryid) MATCH FULL ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: countries currencies_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.countries
    ADD CONSTRAINT currencies_fk FOREIGN KEY (currencyid) REFERENCES public.currencies(currencyid);


--
-- Name: currencynames currencies_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.currencynames
    ADD CONSTRAINT currencies_fk FOREIGN KEY (currencyid) REFERENCES public.currencies(currencyid) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: exchangerates currencies_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.exchangerates
    ADD CONSTRAINT currencies_fk FOREIGN KEY (currencyid) REFERENCES public.currencies(currencyid) MATCH FULL ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: languagenames lang_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.languagenames
    ADD CONSTRAINT lang_fk FOREIGN KEY (language) REFERENCES public.languages(languageid) MATCH FULL ON DELETE CASCADE;


--
-- Name: countrynames languages_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.countrynames
    ADD CONSTRAINT languages_fk FOREIGN KEY (languageid) REFERENCES public.languages(languageid) MATCH FULL ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: currencynames languages_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.currencynames
    ADD CONSTRAINT languages_fk FOREIGN KEY (languageid) REFERENCES public.languages(languageid) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: languagenames languages_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.languagenames
    ADD CONSTRAINT languages_fk FOREIGN KEY (languageid) REFERENCES public.languages(languageid) MATCH FULL ON DELETE CASCADE;


--
-- Name: languagevariants languages_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.languagevariants
    ADD CONSTRAINT languages_fk FOREIGN KEY (languageid) REFERENCES public.languages(languageid) MATCH FULL ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: statenames languages_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.statenames
    ADD CONSTRAINT languages_fk FOREIGN KEY (languageid) REFERENCES public.languages(languageid) MATCH FULL ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: statenames states_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.statenames
    ADD CONSTRAINT states_fk FOREIGN KEY (stateid) REFERENCES public.states(stateid) MATCH FULL ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- PostgreSQL database dump complete
--

-- 1 down
-- (public is the default schema; not dropped)
