-- 1 up
--
-- PostgreSQL database dump
--


-- Dumped from database version 16.14 (Ubuntu 16.14-0ubuntu0.24.04.1)
-- Dumped by pg_dump version 16.14 (Ubuntu 16.14-0ubuntu0.24.04.1)


--
-- Name: poll; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA IF NOT EXISTS poll;




--
-- Name: polls; Type: TABLE; Schema: poll; Owner: -
--

CREATE TABLE poll.polls (
    pollid integer NOT NULL,
    created timestamp with time zone DEFAULT now() NOT NULL,
    tail smallint DEFAULT 10 NOT NULL,
    count integer DEFAULT 0 NOT NULL,
    active boolean DEFAULT true NOT NULL
);


--
-- Name: polls_pollid_seq; Type: SEQUENCE; Schema: poll; Owner: -
--

ALTER TABLE poll.polls ALTER COLUMN pollid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME poll.polls_pollid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: polltranslations; Type: TABLE; Schema: poll; Owner: -
--

CREATE TABLE poll.polltranslations (
    polltranslationid bigint NOT NULL,
    languageid integer NOT NULL,
    pollid bigint NOT NULL,
    title character varying(191) NOT NULL,
    description text,
    version integer DEFAULT 1 NOT NULL
);


--
-- Name: polltranslations_polltranslationid_seq; Type: SEQUENCE; Schema: poll; Owner: -
--

ALTER TABLE poll.polltranslations ALTER COLUMN polltranslationid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME poll.polltranslations_polltranslationid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: signers; Type: TABLE; Schema: poll; Owner: -
--

CREATE TABLE poll.signers (
    signerid bigint NOT NULL,
    firstname character varying(191) NOT NULL,
    lastname character varying(191) NOT NULL,
    email character varying(191) NOT NULL,
    pc character varying(15),
    city character varying(191) NOT NULL,
    cc character varying(4) NOT NULL,
    ip inet NOT NULL,
    submitted timestamp with time zone DEFAULT now() NOT NULL,
    confirmed timestamp with time zone,
    uuid uuid NOT NULL,
    logotype smallint DEFAULT 0 NOT NULL,
    language character varying(8) DEFAULT 'en'::character varying NOT NULL,
    reviewed smallint DEFAULT 0 NOT NULL,
    pollid integer NOT NULL
);


--
-- Name: COLUMN signers.pc; Type: COMMENT; Schema: poll; Owner: -
--

COMMENT ON COLUMN poll.signers.pc IS 'Postal code';


--
-- Name: COLUMN signers.cc; Type: COMMENT; Schema: poll; Owner: -
--

COMMENT ON COLUMN poll.signers.cc IS 'Country code';


--
-- Name: signers_signerid_seq; Type: SEQUENCE; Schema: poll; Owner: -
--

ALTER TABLE poll.signers ALTER COLUMN signerid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME poll.signers_signerid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: polls polls_pk; Type: CONSTRAINT; Schema: poll; Owner: -
--

ALTER TABLE ONLY poll.polls
    ADD CONSTRAINT polls_pk PRIMARY KEY (pollid);


--
-- Name: polltranslations polltranslations_pk; Type: CONSTRAINT; Schema: poll; Owner: -
--

ALTER TABLE ONLY poll.polltranslations
    ADD CONSTRAINT polltranslations_pk PRIMARY KEY (polltranslationid);


--
-- Name: signers signers_pk; Type: CONSTRAINT; Schema: poll; Owner: -
--

ALTER TABLE ONLY poll.signers
    ADD CONSTRAINT signers_pk PRIMARY KEY (signerid);


--
-- Name: signers uuid_uq; Type: CONSTRAINT; Schema: poll; Owner: -
--

ALTER TABLE ONLY poll.signers
    ADD CONSTRAINT uuid_uq UNIQUE (uuid);


--
-- Name: signers_pollid_idx; Type: INDEX; Schema: poll; Owner: -
--

CREATE INDEX signers_pollid_idx ON poll.signers USING btree (pollid);


--
-- Name: polltranslations languages_fk; Type: FK CONSTRAINT; Schema: poll; Owner: -
--

ALTER TABLE ONLY poll.polltranslations
    ADD CONSTRAINT languages_fk FOREIGN KEY (languageid) REFERENCES public.languages(languageid) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: polltranslations polls_fk; Type: FK CONSTRAINT; Schema: poll; Owner: -
--

ALTER TABLE ONLY poll.polltranslations
    ADD CONSTRAINT polls_fk FOREIGN KEY (pollid) REFERENCES poll.polls(pollid) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: signers polls_fk; Type: FK CONSTRAINT; Schema: poll; Owner: -
--

ALTER TABLE ONLY poll.signers
    ADD CONSTRAINT polls_fk FOREIGN KEY (pollid) REFERENCES poll.polls(pollid) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

-- 1 down
DROP SCHEMA IF EXISTS poll CASCADE;
