-- Migration 19: Mailer schema
-- Date: 2026-01-13
-- Description: Multi-tenant mailer with lists, addresses, and bounce handling

SET search_path=public,pg_catalog,account,customer,mailer;
-- ddl-end --

-- object: mailer | type: SCHEMA --
CREATE SCHEMA mailer;
-- ddl-end --
ALTER SCHEMA mailer OWNER TO samizdat;
-- ddl-end --

-- object: mailer.addresses | type: TABLE --
-- Local address storage (not using account.contacts)
CREATE TABLE mailer.addresses (
    addressid bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    private_id uuid NOT NULL DEFAULT gen_random_uuid(),
    customerid bigint,
    email varchar(255) NOT NULL,
    name varchar(255),
    first_name varchar(127),
    last_name varchar(127),
    languageid integer NOT NULL DEFAULT 1,
    verified boolean NOT NULL DEFAULT false,
    needs_review boolean NOT NULL DEFAULT false,
    source varchar(63) NOT NULL DEFAULT 'import',
    created timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT addresses_pk PRIMARY KEY (addressid),
    CONSTRAINT address_customer_email_uq UNIQUE (customerid, email),
    CONSTRAINT addresses_private_id_uq UNIQUE (private_id)
);
-- ddl-end --
COMMENT ON TABLE mailer.addresses IS E'Email addresses for mailings';
COMMENT ON COLUMN mailer.addresses.private_id IS E'Private identifier for privacy self-service access';
COMMENT ON COLUMN mailer.addresses.customerid IS E'Owner customer for multi-tenant';
COMMENT ON COLUMN mailer.addresses.name IS E'Full name (easier than concatenating first+last)';
COMMENT ON COLUMN mailer.addresses.needs_review IS E'True if name was auto-split and needs manual check';
COMMENT ON COLUMN mailer.addresses.source IS E'import, scrape, purchase, manual, signup';
ALTER TABLE mailer.addresses OWNER TO samizdat;
-- ddl-end --

-- object: mailer.lists | type: TABLE --
-- Mailing lists
CREATE TABLE mailer.lists (
    listid bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    customerid bigint,
    name varchar(191) NOT NULL,
    description text,
    is_public boolean NOT NULL DEFAULT false,
    created timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT lists_pk PRIMARY KEY (listid)
);
-- ddl-end --
COMMENT ON TABLE mailer.lists IS E'Mailing lists for organizing addresses';
ALTER TABLE mailer.lists OWNER TO samizdat;
-- ddl-end --

-- object: mailer.list_addresses | type: TABLE --
-- Many-to-many: lists <-> addresses
CREATE TABLE mailer.list_addresses (
    listid bigint NOT NULL,
    addressid bigint NOT NULL,
    subscribed timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT list_addresses_pk PRIMARY KEY (listid, addressid)
);
-- ddl-end --
COMMENT ON TABLE mailer.list_addresses IS E'Links addresses to lists';
ALTER TABLE mailer.list_addresses OWNER TO samizdat;
-- ddl-end --

-- object: mailer.mails | type: TABLE --
-- Mail campaigns (renamed from notifications)
CREATE TABLE mailer.mails (
    mailid bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    customerid bigint,
    name varchar(191) NOT NULL,
    is_draft boolean NOT NULL DEFAULT true,
    status varchar(31) NOT NULL DEFAULT 'draft',
    scheduled timestamp with time zone,
    started timestamp with time zone,
    completed timestamp with time zone,
    smtp_serverid bigint,
    creator bigint NOT NULL,
    created timestamp with time zone NOT NULL DEFAULT now(),
    modified timestamp with time zone,
    CONSTRAINT mails_pk PRIMARY KEY (mailid)
);
-- ddl-end --
COMMENT ON TABLE mailer.mails IS E'Mail campaigns';
COMMENT ON COLUMN mailer.mails.is_draft IS E'Draft flag - not yet ready for sending';
COMMENT ON COLUMN mailer.mails.status IS E'draft, scheduled, sending, completed, cancelled';
ALTER TABLE mailer.mails OWNER TO samizdat;
-- ddl-end --

-- object: mailer.mail_contents | type: TABLE --
-- Localized mail content
CREATE TABLE mailer.mail_contents (
    contentid bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    mailid bigint NOT NULL,
    languageid integer NOT NULL,
    "from" varchar(255),
    organization varchar(255),
    subject varchar(255) NOT NULL,
    body_md text NOT NULL,
    CONSTRAINT mail_contents_pk PRIMARY KEY (contentid),
    CONSTRAINT mail_content_lang_uq UNIQUE (mailid, languageid)
);
-- ddl-end --
COMMENT ON TABLE mailer.mail_contents IS E'Localized mail content (markdown)';
COMMENT ON COLUMN mailer.mail_contents."from" IS E'Header From display (falls back to config)';
COMMENT ON COLUMN mailer.mail_contents.organization IS E'Organization header (falls back to config)';
ALTER TABLE mailer.mail_contents OWNER TO samizdat;
-- ddl-end --

-- object: mailer.attachments | type: TABLE --
CREATE TABLE mailer.attachments (
    attachmentid bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    contentid bigint NOT NULL,
    filename varchar(255) NOT NULL,
    filepath varchar(511) NOT NULL,
    mimetype varchar(127) NOT NULL DEFAULT 'application/pdf',
    CONSTRAINT attachments_pk PRIMARY KEY (attachmentid)
);
-- ddl-end --
COMMENT ON TABLE mailer.attachments IS E'Localized attachments per content';
ALTER TABLE mailer.attachments OWNER TO samizdat;
-- ddl-end --

-- object: mailer.deliveries | type: TABLE --
-- Per-recipient delivery tracking
CREATE TABLE mailer.deliveries (
    deliveryid bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    mailid bigint NOT NULL,
    email varchar(255) NOT NULL,
    languageid integer NOT NULL,
    customerid bigint,
    addressid bigint,
    status varchar(31) NOT NULL DEFAULT 'pending',
    queued timestamp with time zone NOT NULL DEFAULT now(),
    sent timestamp with time zone,
    error text,
    CONSTRAINT deliveries_pk PRIMARY KEY (deliveryid),
    CONSTRAINT delivery_mail_email_uq UNIQUE (mailid, email)
);
-- ddl-end --
COMMENT ON TABLE mailer.deliveries IS E'Per-recipient delivery tracking';
COMMENT ON COLUMN mailer.deliveries.status IS E'pending, queued, sent, failed';
COMMENT ON COLUMN mailer.deliveries.customerid IS E'For customer mailings';
COMMENT ON COLUMN mailer.deliveries.addressid IS E'For list address mailings';
ALTER TABLE mailer.deliveries OWNER TO samizdat;
-- ddl-end --

-- object: mailer.unsubscriptions | type: TABLE --
CREATE TABLE mailer.unsubscriptions (
    unsubscriptionid bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    email varchar(255) NOT NULL,
    reason varchar(63),
    token uuid NOT NULL DEFAULT gen_random_uuid(),
    created timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT unsubscriptions_pk PRIMARY KEY (unsubscriptionid),
    CONSTRAINT unsubscription_email_uq UNIQUE (email)
);
-- ddl-end --
COMMENT ON TABLE mailer.unsubscriptions IS E'Global unsubscription list';
COMMENT ON COLUMN mailer.unsubscriptions.reason IS E'unsubscribe, bounce, complaint, manual, no_longer_interested, too_many_emails, never_subscribed';
ALTER TABLE mailer.unsubscriptions OWNER TO samizdat;
-- ddl-end --

-- object: mailer.configs | type: TABLE --
-- Per-customer mailer configuration (key/value)
CREATE TABLE mailer.configs (
    configid bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    customerid bigint NOT NULL,
    key varchar(63) NOT NULL,
    value text,
    created timestamp with time zone NOT NULL DEFAULT now(),
    modified timestamp with time zone,
    CONSTRAINT configs_pk PRIMARY KEY (configid),
    CONSTRAINT config_customer_key_uq UNIQUE (customerid, key)
);
-- ddl-end --
COMMENT ON TABLE mailer.configs IS E'Per-customer mailer settings';
COMMENT ON COLUMN mailer.configs.key IS E'sender_name, sender_email, reply_to, etc.';
ALTER TABLE mailer.configs OWNER TO samizdat;
-- ddl-end --

-- object: mailer.smtp_servers | type: TABLE --
CREATE TABLE mailer.smtp_servers (
    serverid bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    customerid bigint NOT NULL,
    name varchar(127) NOT NULL,
    host varchar(255) NOT NULL,
    port integer NOT NULL DEFAULT 587,
    encryption varchar(15) NOT NULL DEFAULT 'starttls',
    username varchar(255),
    password varchar(255),
    auth_method varchar(31) DEFAULT 'plain',
    is_default boolean NOT NULL DEFAULT false,
    active boolean NOT NULL DEFAULT true,
    created timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT smtp_servers_pk PRIMARY KEY (serverid)
);
-- ddl-end --
COMMENT ON TABLE mailer.smtp_servers IS E'SMTP servers for outgoing mail';
COMMENT ON COLUMN mailer.smtp_servers.encryption IS E'none, ssl, starttls';
COMMENT ON COLUMN mailer.smtp_servers.auth_method IS E'plain, login, cram-md5';
ALTER TABLE mailer.smtp_servers OWNER TO samizdat;
-- ddl-end --

-- object: mailer.imap_servers | type: TABLE --
CREATE TABLE mailer.imap_servers (
    serverid bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    customerid bigint NOT NULL,
    name varchar(127) NOT NULL,
    protocol varchar(7) NOT NULL DEFAULT 'imap',
    host varchar(255) NOT NULL,
    port integer NOT NULL DEFAULT 993,
    encryption varchar(15) NOT NULL DEFAULT 'ssl',
    username varchar(255) NOT NULL,
    password varchar(255) NOT NULL,
    folder varchar(127) NOT NULL DEFAULT 'INBOX',
    delete_after_process boolean NOT NULL DEFAULT false,
    active boolean NOT NULL DEFAULT true,
    last_check timestamp with time zone,
    created timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT imap_servers_pk PRIMARY KEY (serverid)
);
-- ddl-end --
COMMENT ON TABLE mailer.imap_servers IS E'IMAP/POP3 servers for bounce processing';
COMMENT ON COLUMN mailer.imap_servers.protocol IS E'imap, pop3';
ALTER TABLE mailer.imap_servers OWNER TO samizdat;
-- ddl-end --

-- object: mailer.bounces | type: TABLE --
CREATE TABLE mailer.bounces (
    bounceid bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    deliveryid bigint,
    email varchar(255) NOT NULL,
    bounce_type varchar(31) NOT NULL DEFAULT 'hard',
    bounce_code varchar(15),
    diagnostic text,
    raw_message text,
    processed boolean NOT NULL DEFAULT false,
    received timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT bounces_pk PRIMARY KEY (bounceid)
);
-- ddl-end --
COMMENT ON TABLE mailer.bounces IS E'Bounce message tracking';
COMMENT ON COLUMN mailer.bounces.bounce_type IS E'hard, soft, complaint, delayed';
COMMENT ON COLUMN mailer.bounces.bounce_code IS E'RFC 3463 status code (e.g., 5.1.1)';
ALTER TABLE mailer.bounces OWNER TO samizdat;
-- ddl-end --

-- object: mailer.stats | type: TABLE --
-- Reading/engagement statistics
CREATE TABLE mailer.stats (
    statid bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    deliveryid bigint,
    mailid bigint,
    email varchar(255),
    stat_type varchar(31) NOT NULL,
    data jsonb,
    created timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT stats_pk PRIMARY KEY (statid)
);
-- ddl-end --
COMMENT ON TABLE mailer.stats IS E'Reading and engagement statistics';
COMMENT ON COLUMN mailer.stats.stat_type IS E'open, click, read_onsite, forward, print';
COMMENT ON COLUMN mailer.stats.data IS E'Additional data like URL clicked, user agent, etc.';
ALTER TABLE mailer.stats OWNER TO samizdat;
-- ddl-end --

-- [ Indexes ] --
CREATE INDEX addresses_customer_idx ON mailer.addresses USING btree (customerid);
CREATE INDEX addresses_email_idx ON mailer.addresses USING btree (email);
CREATE INDEX addresses_source_idx ON mailer.addresses USING btree (source);
CREATE INDEX lists_customer_idx ON mailer.lists USING btree (customerid);
CREATE INDEX mails_customer_idx ON mailer.mails USING btree (customerid);
CREATE INDEX mails_status_idx ON mailer.mails USING btree (status);
CREATE INDEX deliveries_mail_idx ON mailer.deliveries USING btree (mailid);
CREATE INDEX deliveries_status_idx ON mailer.deliveries USING btree (status);
CREATE INDEX configs_customer_idx ON mailer.configs USING btree (customerid);
CREATE INDEX smtp_servers_customer_idx ON mailer.smtp_servers USING btree (customerid);
CREATE INDEX imap_servers_customer_idx ON mailer.imap_servers USING btree (customerid);
CREATE INDEX bounces_email_idx ON mailer.bounces USING btree (email);
CREATE INDEX bounces_received_idx ON mailer.bounces USING btree (received);
CREATE INDEX stats_mail_idx ON mailer.stats USING btree (mailid);
CREATE INDEX stats_type_idx ON mailer.stats USING btree (stat_type);
-- ddl-end --

-- [ Foreign keys ] --

-- addresses
ALTER TABLE mailer.addresses ADD CONSTRAINT customer_fk FOREIGN KEY (customerid)
REFERENCES customer.customers (customerid) MATCH SIMPLE
ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE mailer.addresses ADD CONSTRAINT language_fk FOREIGN KEY (languageid)
REFERENCES public.languages (languageid) MATCH SIMPLE
ON DELETE RESTRICT ON UPDATE CASCADE;

-- lists
ALTER TABLE mailer.lists ADD CONSTRAINT customer_fk FOREIGN KEY (customerid)
REFERENCES customer.customers (customerid) MATCH SIMPLE
ON DELETE CASCADE ON UPDATE CASCADE;

-- list_addresses
ALTER TABLE mailer.list_addresses ADD CONSTRAINT list_fk FOREIGN KEY (listid)
REFERENCES mailer.lists (listid) MATCH SIMPLE
ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE mailer.list_addresses ADD CONSTRAINT address_fk FOREIGN KEY (addressid)
REFERENCES mailer.addresses (addressid) MATCH SIMPLE
ON DELETE CASCADE ON UPDATE CASCADE;

-- mails
ALTER TABLE mailer.mails ADD CONSTRAINT creator_fk FOREIGN KEY (creator)
REFERENCES account.users (userid) MATCH SIMPLE
ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE mailer.mails ADD CONSTRAINT customer_fk FOREIGN KEY (customerid)
REFERENCES customer.customers (customerid) MATCH SIMPLE
ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE mailer.mails ADD CONSTRAINT smtp_server_fk FOREIGN KEY (smtp_serverid)
REFERENCES mailer.smtp_servers (serverid) MATCH SIMPLE
ON DELETE SET NULL ON UPDATE CASCADE;

-- mail_contents
ALTER TABLE mailer.mail_contents ADD CONSTRAINT mail_fk FOREIGN KEY (mailid)
REFERENCES mailer.mails (mailid) MATCH SIMPLE
ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE mailer.mail_contents ADD CONSTRAINT language_fk FOREIGN KEY (languageid)
REFERENCES public.languages (languageid) MATCH SIMPLE
ON DELETE RESTRICT ON UPDATE CASCADE;

-- attachments
ALTER TABLE mailer.attachments ADD CONSTRAINT content_fk FOREIGN KEY (contentid)
REFERENCES mailer.mail_contents (contentid) MATCH SIMPLE
ON DELETE CASCADE ON UPDATE CASCADE;

-- deliveries
ALTER TABLE mailer.deliveries ADD CONSTRAINT mail_fk FOREIGN KEY (mailid)
REFERENCES mailer.mails (mailid) MATCH SIMPLE
ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE mailer.deliveries ADD CONSTRAINT customer_fk FOREIGN KEY (customerid)
REFERENCES customer.customers (customerid) MATCH SIMPLE
ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE mailer.deliveries ADD CONSTRAINT address_fk FOREIGN KEY (addressid)
REFERENCES mailer.addresses (addressid) MATCH SIMPLE
ON DELETE CASCADE ON UPDATE CASCADE;

-- configs
ALTER TABLE mailer.configs ADD CONSTRAINT customer_fk FOREIGN KEY (customerid)
REFERENCES customer.customers (customerid) MATCH SIMPLE
ON DELETE CASCADE ON UPDATE CASCADE;

-- smtp_servers
ALTER TABLE mailer.smtp_servers ADD CONSTRAINT customer_fk FOREIGN KEY (customerid)
REFERENCES customer.customers (customerid) MATCH SIMPLE
ON DELETE CASCADE ON UPDATE CASCADE;

-- imap_servers
ALTER TABLE mailer.imap_servers ADD CONSTRAINT customer_fk FOREIGN KEY (customerid)
REFERENCES customer.customers (customerid) MATCH SIMPLE
ON DELETE CASCADE ON UPDATE CASCADE;

-- bounces
ALTER TABLE mailer.bounces ADD CONSTRAINT delivery_fk FOREIGN KEY (deliveryid)
REFERENCES mailer.deliveries (deliveryid) MATCH SIMPLE
ON DELETE SET NULL ON UPDATE CASCADE;

-- stats
ALTER TABLE mailer.stats ADD CONSTRAINT delivery_fk FOREIGN KEY (deliveryid)
REFERENCES mailer.deliveries (deliveryid) MATCH SIMPLE
ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE mailer.stats ADD CONSTRAINT mail_fk FOREIGN KEY (mailid)
REFERENCES mailer.mails (mailid) MATCH SIMPLE
ON DELETE CASCADE ON UPDATE CASCADE;
