--
-- PostgreSQL database dump
--


-- Dumped from database version 16.14 (Ubuntu 16.14-0ubuntu0.24.04.1)
-- Dumped by pg_dump version 16.14 (Ubuntu 16.14-0ubuntu0.24.04.1)


--
-- Name: article; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA IF NOT EXISTS article;




--
-- Name: articlenames; Type: TABLE; Schema: article; Owner: -
--

CREATE TABLE article.articlenames (
    articlenameid bigint NOT NULL,
    articleid bigint,
    languageid bigint DEFAULT 1,
    articlename character varying(191) NOT NULL
);


--
-- Name: articlenames_articlenameid_seq; Type: SEQUENCE; Schema: article; Owner: -
--

ALTER TABLE article.articlenames ALTER COLUMN articlenameid ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME article.articlenames_articlenameid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: articleprices; Type: TABLE; Schema: article; Owner: -
--

CREATE TABLE article.articleprices (
    articlepriceid bigint NOT NULL,
    articleid bigint,
    currencyid integer,
    price numeric
);


--
-- Name: articleprices_articlepriceid_seq; Type: SEQUENCE; Schema: article; Owner: -
--

ALTER TABLE article.articleprices ALTER COLUMN articlepriceid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME article.articleprices_articlepriceid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: articles; Type: TABLE; Schema: article; Owner: -
--

CREATE TABLE article.articles (
    articleid bigint NOT NULL
);


--
-- Name: articles_articleid_seq; Type: SEQUENCE; Schema: article; Owner: -
--

ALTER TABLE article.articles ALTER COLUMN articleid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME article.articles_articleid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: articlevatrates; Type: TABLE; Schema: article; Owner: -
--

CREATE TABLE article.articlevatrates (
    articlevatrateid integer NOT NULL,
    vatrateid integer,
    articleid bigint
);


--
-- Name: articlevatrates_articlevatrateid_seq; Type: SEQUENCE; Schema: article; Owner: -
--

ALTER TABLE article.articlevatrates ALTER COLUMN articlevatrateid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME article.articlevatrates_articlevatrateid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: articlenames articlenames_pk; Type: CONSTRAINT; Schema: article; Owner: -
--

ALTER TABLE ONLY article.articlenames
    ADD CONSTRAINT articlenames_pk PRIMARY KEY (articlenameid);


--
-- Name: articleprices articleprices_pk; Type: CONSTRAINT; Schema: article; Owner: -
--

ALTER TABLE ONLY article.articleprices
    ADD CONSTRAINT articleprices_pk PRIMARY KEY (articlepriceid);


--
-- Name: articles articles_pk; Type: CONSTRAINT; Schema: article; Owner: -
--

ALTER TABLE ONLY article.articles
    ADD CONSTRAINT articles_pk PRIMARY KEY (articleid);


--
-- Name: articlevatrates articlevatrates_pk; Type: CONSTRAINT; Schema: article; Owner: -
--

ALTER TABLE ONLY article.articlevatrates
    ADD CONSTRAINT articlevatrates_pk PRIMARY KEY (articlevatrateid);


--
-- Name: articleprices articles_fd; Type: FK CONSTRAINT; Schema: article; Owner: -
--

ALTER TABLE ONLY article.articleprices
    ADD CONSTRAINT articles_fd FOREIGN KEY (articleid) REFERENCES article.articles(articleid) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: articlenames articles_fk; Type: FK CONSTRAINT; Schema: article; Owner: -
--

ALTER TABLE ONLY article.articlenames
    ADD CONSTRAINT articles_fk FOREIGN KEY (articlenameid) REFERENCES article.articles(articleid) ON DELETE CASCADE;


--
-- Name: articlevatrates articles_fk; Type: FK CONSTRAINT; Schema: article; Owner: -
--

ALTER TABLE ONLY article.articlevatrates
    ADD CONSTRAINT articles_fk FOREIGN KEY (articleid) REFERENCES article.articles(articleid) ON DELETE CASCADE;


--
-- Name: articleprices currencies_fk; Type: FK CONSTRAINT; Schema: article; Owner: -
--

ALTER TABLE ONLY article.articleprices
    ADD CONSTRAINT currencies_fk FOREIGN KEY (currencyid) REFERENCES public.currencies(currencyid) ON DELETE SET NULL;


--
-- Name: articlenames languages_fk; Type: FK CONSTRAINT; Schema: article; Owner: -
--

ALTER TABLE ONLY article.articlenames
    ADD CONSTRAINT languages_fk FOREIGN KEY (articlenameid) REFERENCES public.languages(languageid) ON DELETE CASCADE;


--
-- Name: articlevatrates vatrates_fk; Type: FK CONSTRAINT; Schema: article; Owner: -
--

ALTER TABLE ONLY article.articlevatrates
    ADD CONSTRAINT vatrates_fk FOREIGN KEY (vatrateid) REFERENCES public.vatrates(vatrateid) ON DELETE SET NULL;


--
-- PostgreSQL database dump complete
--
