-- CSP (Content Security Policy) module for OpenResty
-- Reads companion .csp files generated by Samizdat and applies them as headers
--
-- Usage in nginx.conf:
--   lua_shared_dict csp_cache 10m;
--   lua_package_path "/path/to/samizdat/?.lua;;";
--   init_by_lua_block { csp = require "csp" }
--
-- Then in location blocks:
--   header_filter_by_lua_block { csp.apply() }

local _M = {}

function _M.apply()
    local cache = ngx.shared.csp_cache
    if not cache then
        ngx.log(ngx.ERR, "csp_cache shared dict not defined")
        return
    end

    local uri = ngx.var.uri
    if uri:match("/$") then
        uri = uri .. "index.html"
    end

    -- Include document_root in cache key for multi-vhost support
    local cache_key = ngx.var.document_root .. uri

    local csp = cache:get(cache_key)
    if csp == nil then
        local path = cache_key .. ".csp"
        local f = io.open(path, "r")
        if f then
            csp = f:read("*all") or ""
            f:close()
        else
            csp = ""
        end
        -- Cache for 1 hour (3600 seconds)
        cache:set(cache_key, csp, 3600)
    end

    if csp ~= "" then
        ngx.header["Content-Security-Policy"] = csp
    end
end

-- Clear cache for a specific path (useful after regenerating static files)
function _M.clear(document_root, uri)
    local cache = ngx.shared.csp_cache
    if cache then
        if uri:match("/$") then
            uri = uri .. "index.html"
        end
        cache:delete(document_root .. uri)
    end
end

-- Clear entire cache
function _M.flush()
    local cache = ngx.shared.csp_cache
    if cache then
        cache:flush_all()
    end
end

return _M
