-- Diff code generated with pgModeler (PostgreSQL Database Modeler)
-- pgModeler version: 1.1.0-beta1
-- Diff date: 2025-12-05 23:00:48
-- Source model: samizdat
-- Database: samizdat
-- PostgreSQL version: 16.0

-- [ Diff summary ]
-- Dropped objects: 0
-- Created objects: 5
-- Changed objects: 0

SET search_path=public,pg_catalog,zone;
-- ddl-end --


-- [ Created objects ] --
-- object: zone | type: SCHEMA --
-- DROP SCHEMA IF EXISTS zone CASCADE;
CREATE SCHEMA zone;
-- ddl-end --
ALTER SCHEMA zone OWNER TO samizdat;
-- ddl-end --

-- object: zone.templates | type: TABLE --
-- DROP TABLE IF EXISTS zone.templates CASCADE;
CREATE TABLE zone.templates (
	templateid bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	customerid bigint,
	name varchar(255) NOT NULL,
	description varchar(255) NOT NULL DEFAULT '',
	CONSTRAINT domain_templates_pk PRIMARY KEY (templateid)
);
-- ddl-end --
ALTER TABLE zone.templates OWNER TO samizdat;
-- ddl-end --

-- object: zone.template_records | type: TABLE --
-- DROP TABLE IF EXISTS zone.template_records CASCADE;
CREATE TABLE zone.template_records (
	recordid bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	name varchar(255) NOT NULL,
	type varchar(10) NOT NULL,
	content varchar(65535) NOT NULL,
	ttl integer NOT NULL DEFAULT 3600,
	disabled boolean NOT NULL DEFAULT false,
	templateid_templates bigint NOT NULL,
	CONSTRAINT template_records_pk PRIMARY KEY (recordid)
);
-- ddl-end --
ALTER TABLE zone.template_records OWNER TO samizdat;
-- ddl-end --

-- object: customerid_idx | type: INDEX --
-- DROP INDEX IF EXISTS zone.customerid_idx CASCADE;
CREATE INDEX customerid_idx ON zone.templates
USING btree
(
	customerid
);
-- ddl-end --



-- [ Created foreign keys ] --
-- object: templates_fk | type: CONSTRAINT --
-- ALTER TABLE zone.template_records DROP CONSTRAINT IF EXISTS templates_fk CASCADE;
ALTER TABLE zone.template_records ADD CONSTRAINT templates_fk FOREIGN KEY (templateid_templates)
REFERENCES zone.templates (templateid) MATCH FULL
ON DELETE CASCADE ON UPDATE CASCADE;
-- ddl-end --

