-- object: web.servertype | type: TABLE --
-- DROP TABLE IF EXISTS web.servertype CASCADE;
CREATE TABLE web.servertype (
                              servertypeid bigint NOT NULL GENERATED ALWAYS AS IDENTITY ,
                              servertypename varchar(255) NOT NULL,
                              CONSTRAINT servertype_pk PRIMARY KEY (servertypeid)
);
-- ddl-end --
ALTER TABLE web.servertype OWNER TO samizdat;
-- ddl-end --

-- object: web.server | type: TABLE --
-- DROP TABLE IF EXISTS web.server CASCADE;
CREATE TABLE web.server (
	serverid bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	hostname varchar(255) NOT NULL,
	jailname varchar(255),
	servertypeid bigint,
	CONSTRAINT server_pk PRIMARY KEY (serverid)
);
-- ddl-end --
ALTER TABLE web.server OWNER TO samizdat;
-- ddl-end --

ALTER TABLE web.webservices
  ADD COLUMN IF NOT EXISTS serverid bigint,
  ADD COLUMN IF NOT EXISTS passwordid bigint,
  ADD COLUMN IF NOT EXISTS customerid bigint,
  ADD COLUMN IF NOT EXISTS active smallint DEFAULT 1,
  ADD COLUMN IF NOT EXISTS redirecturl varchar(255);


ALTER TABLE web.domains
  ADD COLUMN IF NOT EXISTS active smallint DEFAULT 1,
  ADD COLUMN IF NOT EXISTS customerid bigint;

-- object: servers_servertypeid_fk | type: CONSTRAINT --
-- ALTER TABLE web.server DROP CONSTRAINT IF EXISTS servers_servertypeid_fk CASCADE;
ALTER TABLE web.server ADD CONSTRAINT servers_servertypeid_fk FOREIGN KEY (servertypeid)
  REFERENCES web.servertype (servertypeid) MATCH SIMPLE
  ON DELETE SET NULL ON UPDATE CASCADE;
-- ddl-end --

-- object: serverid_fk | type: CONSTRAINT --
-- ALTER TABLE web.webservices DROP CONSTRAINT IF EXISTS serverid_fk CASCADE;
ALTER TABLE web.webservices ADD CONSTRAINT serverid_fk FOREIGN KEY (serverid)
  REFERENCES web.server (serverid) MATCH SIMPLE
  ON DELETE SET NULL ON UPDATE CASCADE;
-- ddl-end --

-- object: passwordid_fk | type: CONSTRAINT --
-- ALTER TABLE web.webservices DROP CONSTRAINT IF EXISTS passwordid_fk CASCADE;
ALTER TABLE web.webservices ADD CONSTRAINT passwordid_fk FOREIGN KEY (passwordid)
  REFERENCES account.passwords (passwordid) MATCH SIMPLE
  ON DELETE CASCADE ON UPDATE CASCADE;
-- ddl-end --

-- object: webservers_customerid_fk | type: CONSTRAINT --
-- ALTER TABLE web.webservices DROP CONSTRAINT IF EXISTS webservers_customerid_fk CASCADE;
ALTER TABLE web.webservices ADD CONSTRAINT webservers_customerid_fk FOREIGN KEY (customerid)
  REFERENCES customer.customers (customerid) MATCH SIMPLE
  ON DELETE SET NULL ON UPDATE CASCADE;
-- ddl-end --

-- object: domains_customerid_fk | type: CONSTRAINT --
-- ALTER TABLE web.domains DROP CONSTRAINT IF EXISTS domains_customerid_fk CASCADE;
ALTER TABLE web.domains ADD CONSTRAINT domains_customerid_fk FOREIGN KEY (customerid)
  REFERENCES customer.customers (customerid) MATCH SIMPLE
  ON DELETE SET NULL ON UPDATE NO ACTION;
-- ddl-end --
