-- Migration 24: Split web schema into web (app) and website (hosting)
-- Creates new schemas: website, certificate
-- Moves webservices/domains from web to website, renames to websites
-- Renames webserviceid -> websiteid throughout

SET search_path TO public,pg_catalog,web,account,customer,website,certificate;

-- 0. Fix CHAR columns that pad with whitespace (should be VARCHAR)
ALTER TABLE account.contacts ALTER COLUMN city TYPE varchar(63);

-- 1. Create new schemas
CREATE SCHEMA IF NOT EXISTS website;
ALTER SCHEMA website OWNER TO samizdat;

CREATE SCHEMA IF NOT EXISTS certificate;
ALTER SCHEMA certificate OWNER TO samizdat;

-- 2. Create lookup tables first (no dependencies)

-- Certificate issuers (e.g., Let's Encrypt, DigiCert)
CREATE TABLE certificate.issuers (
  issuerid bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  issuername varchar(255),
  CONSTRAINT issuers_pk PRIMARY KEY (issuerid)
);
ALTER TABLE certificate.issuers OWNER TO samizdat;

-- Server types (e.g., nginx, apache2, mojolicious)
CREATE TABLE website.servertypes (
  servertypeid bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  servertypename varchar(255) NOT NULL,
  CONSTRAINT servertypes_pk PRIMARY KEY (servertypeid)
);
COMMENT ON TABLE website.servertypes IS 'Server software types (nginx, apache2, mojolicious, etc.)';
ALTER TABLE website.servertypes OWNER TO samizdat;

-- Shells (e.g., /bin/ftponly, /bin/bash)
CREATE TABLE website.shells (
  shellid bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  shell varchar(255),
  CONSTRAINT shells_pk PRIMARY KEY (shellid)
);
ALTER TABLE website.shells OWNER TO samizdat;

-- 3. Create dependent tables

-- SSL Certificates
CREATE TABLE certificate.certificates (
  certificateid bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  customerid bigint,
  value text,
  fullvalue text,
  notafter timestamp,
  keyfile varchar(255),
  certfile varchar(255),
  hash varchar(255) NOT NULL,
  issuerid bigint,
  CONSTRAINT certificates_pk PRIMARY KEY (certificateid)
);
ALTER TABLE certificate.certificates OWNER TO samizdat;

ALTER TABLE certificate.certificates ADD CONSTRAINT certificates_issuerid_fk
  FOREIGN KEY (issuerid) REFERENCES certificate.issuers (issuerid)
  ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE certificate.certificates ADD CONSTRAINT certificates_customerid_fk
  FOREIGN KEY (customerid) REFERENCES customer.customers (customerid)
  ON DELETE SET NULL ON UPDATE CASCADE;

-- Servers (with default IPs)
CREATE TABLE website.servers (
  serverid bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  hostname varchar(255) NOT NULL,
  jailname varchar(255),
  servertypeid bigint,
  default_ip4 inet,
  default_ip6 inet,
  CONSTRAINT servers_pk PRIMARY KEY (serverid)
);
COMMENT ON TABLE website.servers IS 'Physical/virtual servers with default IP addresses';
ALTER TABLE website.servers OWNER TO samizdat;

ALTER TABLE website.servers ADD CONSTRAINT servers_servertypeid_fk
  FOREIGN KEY (servertypeid) REFERENCES website.servertypes (servertypeid)
  ON DELETE SET NULL ON UPDATE CASCADE;

-- 4. Add new columns to web.webservices before moving
ALTER TABLE web.webservices
  ADD COLUMN IF NOT EXISTS customerid bigint,
  ADD COLUMN IF NOT EXISTS serverid bigint,
  ADD COLUMN IF NOT EXISTS passwordid bigint,
  ADD COLUMN IF NOT EXISTS certificateid bigint,
  ADD COLUMN IF NOT EXISTS shellid bigint,
  ADD COLUMN IF NOT EXISTS ip4 inet,
  ADD COLUMN IF NOT EXISTS ip6 inet,
  ADD COLUMN IF NOT EXISTS ip_only boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS redirecturl varchar(255),
  ADD COLUMN IF NOT EXISTS active smallint DEFAULT 1,
  ADD COLUMN IF NOT EXISTS web_usage bigint NOT NULL DEFAULT 0;

COMMENT ON COLUMN web.webservices.ip4 IS 'IPv4 address override (null = use server default)';
COMMENT ON COLUMN web.webservices.ip6 IS 'IPv6 address override (null = use server default)';
COMMENT ON COLUMN web.webservices.ip_only IS 'Bind to IP only, no hostname (catch-all for domain parking)';

-- Rename 'path' to 'home' (matches new model)
ALTER TABLE web.webservices RENAME COLUMN path TO home;

-- Rename webserviceid to websiteid
ALTER TABLE web.webservices RENAME COLUMN webserviceid TO websiteid;

-- Add new columns to web.domains before moving
ALTER TABLE web.domains
  ADD COLUMN IF NOT EXISTS customerid bigint,
  ADD COLUMN IF NOT EXISTS incert boolean NOT NULL DEFAULT true;

-- Rename webserviceid to websiteid in domains
ALTER TABLE web.domains RENAME COLUMN webserviceid TO websiteid;

-- 5. Drop old FK constraints that reference the tables we're moving
ALTER TABLE web.resources DROP CONSTRAINT IF EXISTS webservices_fk;
ALTER TABLE web.menus DROP CONSTRAINT IF EXISTS webservices_fk;
ALTER TABLE web.webservices DROP CONSTRAINT IF EXISTS primarydomain_fk;
ALTER TABLE web.domains DROP CONSTRAINT IF EXISTS webservices_fk;

-- 6. Rename webserviceid columns throughout
ALTER TABLE web.resources RENAME COLUMN webserviceid TO websiteid;
ALTER TABLE web.menus RENAME COLUMN webserviceid TO websiteid;
ALTER TABLE customer.services RENAME COLUMN webserviceid TO websiteid;

-- 7. Move and rename tables to website schema
ALTER TABLE web.webservices SET SCHEMA website;
ALTER TABLE website.webservices RENAME TO websites;
ALTER SEQUENCE website.webservices_webserviceid_seq RENAME TO websites_websiteid_seq;

ALTER TABLE web.domains SET SCHEMA website;

-- 8. Create config tables (depend on websites)
CREATE TABLE website.serverextras (
  serverextraid bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  configextra text,
  websiteid bigint NOT NULL,
  active boolean NOT NULL DEFAULT true,
  CONSTRAINT serverextras_pk PRIMARY KEY (serverextraid)
);
COMMENT ON TABLE website.serverextras IS 'Extra configuration directives for Apache/Nginx';
ALTER TABLE website.serverextras OWNER TO samizdat;

ALTER TABLE website.serverextras ADD CONSTRAINT serverextras_websiteid_fk
  FOREIGN KEY (websiteid) REFERENCES website.websites (websiteid)
  ON DELETE CASCADE ON UPDATE CASCADE;

CREATE TABLE website.phpconfigs (
  phpconfigid bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  phpconfig text,
  websiteid bigint NOT NULL,
  active boolean NOT NULL DEFAULT true,
  CONSTRAINT phpconfigs_pk PRIMARY KEY (phpconfigid)
);
COMMENT ON TABLE website.phpconfigs IS 'PHP-FPM pool configuration, merged with .php.conf';
ALTER TABLE website.phpconfigs OWNER TO samizdat;

ALTER TABLE website.phpconfigs ADD CONSTRAINT phpconfigs_websiteid_fk
  FOREIGN KEY (websiteid) REFERENCES website.websites (websiteid)
  ON DELETE CASCADE ON UPDATE CASCADE;

-- 9. Add FK constraints in new schema

-- websites FKs
ALTER TABLE website.websites ADD CONSTRAINT websites_primarydomain_fk
  FOREIGN KEY (primarydomain) REFERENCES website.domains (domainid)
  ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE website.websites ADD CONSTRAINT websites_serverid_fk
  FOREIGN KEY (serverid) REFERENCES website.servers (serverid)
  ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE website.websites ADD CONSTRAINT websites_passwordid_fk
  FOREIGN KEY (passwordid) REFERENCES account.passwords (passwordid)
  ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE website.websites ADD CONSTRAINT websites_certificateid_fk
  FOREIGN KEY (certificateid) REFERENCES certificate.certificates (certificateid)
  ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE website.websites ADD CONSTRAINT websites_customerid_fk
  FOREIGN KEY (customerid) REFERENCES customer.customers (customerid)
  ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE website.websites ADD CONSTRAINT websites_shellid_fk
  FOREIGN KEY (shellid) REFERENCES website.shells (shellid)
  ON DELETE SET NULL ON UPDATE CASCADE;

-- domains FKs
ALTER TABLE website.domains ADD CONSTRAINT domains_websiteid_fk
  FOREIGN KEY (websiteid) REFERENCES website.websites (websiteid)
  ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE website.domains ADD CONSTRAINT domains_customerid_fk
  FOREIGN KEY (customerid) REFERENCES customer.customers (customerid)
  ON DELETE SET NULL ON UPDATE CASCADE;

-- 10. Re-add FK constraints from other schemas to website
ALTER TABLE web.resources ADD CONSTRAINT resources_websiteid_fk
  FOREIGN KEY (websiteid) REFERENCES website.websites (websiteid)
  ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE web.menus ADD CONSTRAINT menus_websiteid_fk
  FOREIGN KEY (websiteid) REFERENCES website.websites (websiteid)
  ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE customer.services ADD CONSTRAINT services_websiteid_fk
  FOREIGN KEY (websiteid) REFERENCES website.websites (websiteid)
  ON DELETE SET NULL ON UPDATE CASCADE;
