-- Migration 22: Database management schema

SET search_path=public,pg_catalog,customer;

-- Create schema
CREATE SCHEMA IF NOT EXISTS database;
ALTER SCHEMA database OWNER TO samizdat;

-- Database types lookup table (create first for FK reference)
CREATE TABLE database.databasetypes (
	databasetypeid bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	databasetypename varchar(32) NOT NULL,
	CONSTRAINT databasetypes_pk PRIMARY KEY (databasetypeid),
	CONSTRAINT databasetypename_uq UNIQUE (databasetypename)
);
ALTER TABLE database.databasetypes OWNER TO samizdat;

-- Databases table
CREATE TABLE database.databases (
	databaseid bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	customerid bigint NOT NULL DEFAULT 0,
	databasetypeid bigint NOT NULL DEFAULT 1,
	databasename varchar(255) NOT NULL,
	username varchar(64) NOT NULL DEFAULT '',
	password varchar(255) NOT NULL DEFAULT '',
	created timestamptz NOT NULL DEFAULT NOW(),
	creator varchar(255) NOT NULL DEFAULT '',
	updated timestamptz NOT NULL DEFAULT NOW(),
	updater varchar(255) NOT NULL DEFAULT '',
	db_usage bigint NOT NULL DEFAULT 0,
	CONSTRAINT databases_pk PRIMARY KEY (databaseid),
	CONSTRAINT databasename_uq UNIQUE (databasename)
);
ALTER TABLE database.databases OWNER TO samizdat;

-- Foreign keys
ALTER TABLE database.databases ADD CONSTRAINT databases_customerid_fk FOREIGN KEY (customerid)
	REFERENCES customer.customers (customerid) MATCH SIMPLE
	ON DELETE SET DEFAULT ON UPDATE NO ACTION;

ALTER TABLE database.databases ADD CONSTRAINT databases_databasetypeid_fk FOREIGN KEY (databasetypeid)
	REFERENCES database.databasetypes (databasetypeid) MATCH SIMPLE
	ON DELETE NO ACTION ON UPDATE CASCADE;