--
-- PostgreSQL database dump
--


-- Dumped from database version 16.14 (Ubuntu 16.14-0ubuntu0.24.04.1)
-- Dumped by pg_dump version 16.14 (Ubuntu 16.14-0ubuntu0.24.04.1)


--
-- Name: web; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA IF NOT EXISTS web;




--
-- Name: comments; Type: TABLE; Schema: web; Owner: -
--

CREATE TABLE web.comments (
    commentid bigint NOT NULL,
    parentid bigint,
    resourceid bigint NOT NULL,
    created timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: comments_commentid_seq; Type: SEQUENCE; Schema: web; Owner: -
--

ALTER TABLE web.comments ALTER COLUMN commentid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME web.comments_commentid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: contenttypes; Type: TABLE; Schema: web; Owner: -
--

CREATE TABLE web.contenttypes (
    contenttypeid integer NOT NULL,
    name character varying NOT NULL,
    mimetype character varying(31) NOT NULL
);


--
-- Name: contenttypes_contenttypeid_seq; Type: SEQUENCE; Schema: web; Owner: -
--

ALTER TABLE web.contenttypes ALTER COLUMN contenttypeid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME web.contenttypes_contenttypeid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: contexts; Type: TABLE; Schema: web; Owner: -
--

CREATE TABLE web.contexts (
    contextid integer NOT NULL,
    name character varying NOT NULL
);


--
-- Name: contexts_contextid_seq; Type: SEQUENCE; Schema: web; Owner: -
--

ALTER TABLE web.contexts ALTER COLUMN contextid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME web.contexts_contextid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: homes; Type: TABLE; Schema: web; Owner: -
--

CREATE TABLE web.homes (
    homeid bigint NOT NULL,
    homedir character varying DEFAULT gen_random_uuid() NOT NULL,
    userid bigint NOT NULL
);


--
-- Name: homes_homeid_seq; Type: SEQUENCE; Schema: web; Owner: -
--

ALTER TABLE web.homes ALTER COLUMN homeid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME web.homes_homeid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: menuitems; Type: TABLE; Schema: web; Owner: -
--

CREATE TABLE web.menuitems (
    menuitemid integer NOT NULL,
    parentid integer,
    "position" smallint DEFAULT 0 NOT NULL,
    uriid integer,
    menuid integer NOT NULL,
    children integer DEFAULT 0 NOT NULL
);


--
-- Name: menuitems_menuitemid_seq; Type: SEQUENCE; Schema: web; Owner: -
--

ALTER TABLE web.menuitems ALTER COLUMN menuitemid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME web.menuitems_menuitemid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: menuitemtitles; Type: TABLE; Schema: web; Owner: -
--

CREATE TABLE web.menuitemtitles (
    menuitemtitles integer NOT NULL,
    title character varying(191) NOT NULL,
    menuitemid integer,
    languageid integer DEFAULT 1 NOT NULL
);


--
-- Name: menuitemtitles_menuitemtitles_seq; Type: SEQUENCE; Schema: web; Owner: -
--

ALTER TABLE web.menuitemtitles ALTER COLUMN menuitemtitles ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME web.menuitemtitles_menuitemtitles_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: menus; Type: TABLE; Schema: web; Owner: -
--

CREATE TABLE web.menus (
    menuid integer NOT NULL,
    name character varying DEFAULT ''::character varying NOT NULL,
    websiteid bigint NOT NULL
);


--
-- Name: menus_menuid_seq; Type: SEQUENCE; Schema: web; Owner: -
--

ALTER TABLE web.menus ALTER COLUMN menuid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME web.menus_menuid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: metaconnections; Type: TABLE; Schema: web; Owner: -
--

CREATE TABLE web.metaconnections (
    resourceid bigint NOT NULL,
    metavalueid bigint NOT NULL
);


--
-- Name: COLUMN metaconnections.metavalueid; Type: COMMENT; Schema: web; Owner: -
--

COMMENT ON COLUMN web.metaconnections.metavalueid IS 'links to all language versions';


--
-- Name: metakeys; Type: TABLE; Schema: web; Owner: -
--

CREATE TABLE web.metakeys (
    metakeyid integer NOT NULL,
    metakey character varying NOT NULL
);


--
-- Name: COLUMN metakeys.metakey; Type: COMMENT; Schema: web; Owner: -
--

COMMENT ON COLUMN web.metakeys.metakey IS '''tags'', ''categories'', etc.';


--
-- Name: metakeys_metakeyid_seq; Type: SEQUENCE; Schema: web; Owner: -
--

CREATE SEQUENCE web.metakeys_metakeyid_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: metakeys_metakeyid_seq; Type: SEQUENCE OWNED BY; Schema: web; Owner: -
--

ALTER SEQUENCE web.metakeys_metakeyid_seq OWNED BY web.metakeys.metakeyid;


--
-- Name: metavalues; Type: TABLE; Schema: web; Owner: -
--

CREATE TABLE web.metavalues (
    metavalueid integer NOT NULL,
    metavalue character varying,
    metakeyid bigint NOT NULL,
    languageid bigint DEFAULT 1 NOT NULL
);


--
-- Name: COLUMN metavalues.metavalueid; Type: COMMENT; Schema: web; Owner: -
--

COMMENT ON COLUMN web.metavalues.metavalueid IS 'shared across languages for same concept';


--
-- Name: COLUMN metavalues.metavalue; Type: COMMENT; Schema: web; Owner: -
--

COMMENT ON COLUMN web.metavalues.metavalue IS 'localized value: ''one'', ''en'', ''ein''';


--
-- Name: metavalues_metavalueid_seq; Type: SEQUENCE; Schema: web; Owner: -
--

CREATE SEQUENCE web.metavalues_metavalueid_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: metavalues_metavalueid_seq; Type: SEQUENCE OWNED BY; Schema: web; Owner: -
--

ALTER SEQUENCE web.metavalues_metavalueid_seq OWNED BY web.metavalues.metavalueid;


--
-- Name: resourceconnections; Type: TABLE; Schema: web; Owner: -
--

CREATE TABLE web.resourceconnections (
    resourceconnectionid bigint NOT NULL,
    parent bigint NOT NULL,
    child bigint NOT NULL
);


--
-- Name: resourceconnections_resourceconnectionid_seq; Type: SEQUENCE; Schema: web; Owner: -
--

ALTER TABLE web.resourceconnections ALTER COLUMN resourceconnectionid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME web.resourceconnections_resourceconnectionid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: resources; Type: TABLE; Schema: web; Owner: -
--

CREATE TABLE web.resources (
    resourceid bigint NOT NULL,
    alias character varying DEFAULT ''::character varying NOT NULL,
    content text DEFAULT ''::text NOT NULL,
    owner bigint NOT NULL,
    creator bigint,
    publisher bigint,
    resourcealias bigint,
    contenttype integer DEFAULT 1 NOT NULL,
    languageid integer NOT NULL,
    created timestamp with time zone DEFAULT now() NOT NULL,
    modified timestamp with time zone DEFAULT now() NOT NULL,
    published timestamp with time zone,
    comments integer DEFAULT 0 NOT NULL,
    templateid integer NOT NULL,
    websiteid bigint NOT NULL,
    src character varying DEFAULT ''::character varying NOT NULL
);


--
-- Name: COLUMN resources.resourcealias; Type: COMMENT; Schema: web; Owner: -
--

COMMENT ON COLUMN web.resources.resourcealias IS 'Självreferens';


--
-- Name: COLUMN resources.src; Type: COMMENT; Schema: web; Owner: -
--

COMMENT ON COLUMN web.resources.src IS 'Markdown source file in src tree.';


--
-- Name: resources_resourceid_seq; Type: SEQUENCE; Schema: web; Owner: -
--

ALTER TABLE web.resources ALTER COLUMN resourceid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME web.resources_resourceid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: settings; Type: TABLE; Schema: web; Owner: -
--

CREATE TABLE web.settings (
    settingid integer NOT NULL,
    key character varying NOT NULL,
    value character varying NOT NULL,
    title character varying(191) NOT NULL
);


--
-- Name: settings_settingid_seq; Type: SEQUENCE; Schema: web; Owner: -
--

ALTER TABLE web.settings ALTER COLUMN settingid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME web.settings_settingid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: templates; Type: TABLE; Schema: web; Owner: -
--

CREATE TABLE web.templates (
    templateid integer NOT NULL,
    path character varying DEFAULT 'default.html.ep'::character varying NOT NULL
);


--
-- Name: templates_templateid_seq; Type: SEQUENCE; Schema: web; Owner: -
--

ALTER TABLE web.templates ALTER COLUMN templateid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME web.templates_templateid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: uris; Type: TABLE; Schema: web; Owner: -
--

CREATE TABLE web.uris (
    uriid bigint NOT NULL,
    path character varying DEFAULT ''::character varying NOT NULL,
    resourceid bigint
);


--
-- Name: uris_uriid_seq; Type: SEQUENCE; Schema: web; Owner: -
--

ALTER TABLE web.uris ALTER COLUMN uriid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME web.uris_uriid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: metakeys metakeyid; Type: DEFAULT; Schema: web; Owner: -
--

ALTER TABLE ONLY web.metakeys ALTER COLUMN metakeyid SET DEFAULT nextval('web.metakeys_metakeyid_seq'::regclass);


--
-- Name: metavalues metavalueid; Type: DEFAULT; Schema: web; Owner: -
--

ALTER TABLE ONLY web.metavalues ALTER COLUMN metavalueid SET DEFAULT nextval('web.metavalues_metavalueid_seq'::regclass);


--
-- Name: comments comments_pk; Type: CONSTRAINT; Schema: web; Owner: -
--

ALTER TABLE ONLY web.comments
    ADD CONSTRAINT comments_pk PRIMARY KEY (commentid);


--
-- Name: contenttypes contenttypes_pk; Type: CONSTRAINT; Schema: web; Owner: -
--

ALTER TABLE ONLY web.contenttypes
    ADD CONSTRAINT contenttypes_pk PRIMARY KEY (contenttypeid);


--
-- Name: contexts context_name_uq; Type: CONSTRAINT; Schema: web; Owner: -
--

ALTER TABLE ONLY web.contexts
    ADD CONSTRAINT context_name_uq UNIQUE (name);


--
-- Name: contexts contexts_pk; Type: CONSTRAINT; Schema: web; Owner: -
--

ALTER TABLE ONLY web.contexts
    ADD CONSTRAINT contexts_pk PRIMARY KEY (contextid);


--
-- Name: homes homedir_uq; Type: CONSTRAINT; Schema: web; Owner: -
--

ALTER TABLE ONLY web.homes
    ADD CONSTRAINT homedir_uq UNIQUE (homedir);


--
-- Name: homes homes_pk; Type: CONSTRAINT; Schema: web; Owner: -
--

ALTER TABLE ONLY web.homes
    ADD CONSTRAINT homes_pk PRIMARY KEY (homeid);


--
-- Name: menus menu_name_uq; Type: CONSTRAINT; Schema: web; Owner: -
--

ALTER TABLE ONLY web.menus
    ADD CONSTRAINT menu_name_uq UNIQUE (name);


--
-- Name: menuitems menuitems_pk; Type: CONSTRAINT; Schema: web; Owner: -
--

ALTER TABLE ONLY web.menuitems
    ADD CONSTRAINT menuitems_pk PRIMARY KEY (menuitemid);


--
-- Name: menuitemtitles menuitemtitles_pk; Type: CONSTRAINT; Schema: web; Owner: -
--

ALTER TABLE ONLY web.menuitemtitles
    ADD CONSTRAINT menuitemtitles_pk PRIMARY KEY (menuitemtitles);


--
-- Name: menus menus_pk; Type: CONSTRAINT; Schema: web; Owner: -
--

ALTER TABLE ONLY web.menus
    ADD CONSTRAINT menus_pk PRIMARY KEY (menuid);


--
-- Name: metaconnections metaconnections_pk; Type: CONSTRAINT; Schema: web; Owner: -
--

ALTER TABLE ONLY web.metaconnections
    ADD CONSTRAINT metaconnections_pk PRIMARY KEY (resourceid, metavalueid);


--
-- Name: metakeys metakey_uq; Type: CONSTRAINT; Schema: web; Owner: -
--

ALTER TABLE ONLY web.metakeys
    ADD CONSTRAINT metakey_uq UNIQUE (metakey);


--
-- Name: metakeys metakeys_pk; Type: CONSTRAINT; Schema: web; Owner: -
--

ALTER TABLE ONLY web.metakeys
    ADD CONSTRAINT metakeys_pk PRIMARY KEY (metakeyid);


--
-- Name: metavalues metavalues_pk; Type: CONSTRAINT; Schema: web; Owner: -
--

ALTER TABLE ONLY web.metavalues
    ADD CONSTRAINT metavalues_pk PRIMARY KEY (metakeyid, languageid);


--
-- Name: metavalues metavalues_uq; Type: CONSTRAINT; Schema: web; Owner: -
--

ALTER TABLE ONLY web.metavalues
    ADD CONSTRAINT metavalues_uq UNIQUE (metavalueid);


--
-- Name: contenttypes mimetype_uq; Type: CONSTRAINT; Schema: web; Owner: -
--

ALTER TABLE ONLY web.contenttypes
    ADD CONSTRAINT mimetype_uq UNIQUE (mimetype);


--
-- Name: resources resources_pk; Type: CONSTRAINT; Schema: web; Owner: -
--

ALTER TABLE ONLY web.resources
    ADD CONSTRAINT resources_pk PRIMARY KEY (resourceid);


--
-- Name: settings setting_key_uq; Type: CONSTRAINT; Schema: web; Owner: -
--

ALTER TABLE ONLY web.settings
    ADD CONSTRAINT setting_key_uq UNIQUE (key);


--
-- Name: settings settings_pk; Type: CONSTRAINT; Schema: web; Owner: -
--

ALTER TABLE ONLY web.settings
    ADD CONSTRAINT settings_pk PRIMARY KEY (settingid);


--
-- Name: resources src_lang_uq; Type: CONSTRAINT; Schema: web; Owner: -
--

ALTER TABLE ONLY web.resources
    ADD CONSTRAINT src_lang_uq UNIQUE (src, languageid);


--
-- Name: templates template_path_uq; Type: CONSTRAINT; Schema: web; Owner: -
--

ALTER TABLE ONLY web.templates
    ADD CONSTRAINT template_path_uq UNIQUE (path);


--
-- Name: templates templates_pk; Type: CONSTRAINT; Schema: web; Owner: -
--

ALTER TABLE ONLY web.templates
    ADD CONSTRAINT templates_pk PRIMARY KEY (templateid);


--
-- Name: uris uri_path_uq; Type: CONSTRAINT; Schema: web; Owner: -
--

ALTER TABLE ONLY web.uris
    ADD CONSTRAINT uri_path_uq UNIQUE (path);


--
-- Name: uris uris_pk; Type: CONSTRAINT; Schema: web; Owner: -
--

ALTER TABLE ONLY web.uris
    ADD CONSTRAINT uris_pk PRIMARY KEY (uriid);


--
-- Name: comments_resourceid_idx; Type: INDEX; Schema: web; Owner: -
--

CREATE INDEX comments_resourceid_idx ON web.comments USING btree (resourceid) INCLUDE (resourceid);


--
-- Name: menuitems_menuid_idx; Type: INDEX; Schema: web; Owner: -
--

CREATE INDEX menuitems_menuid_idx ON web.menuitems USING btree (menuid) INCLUDE (menuid);


--
-- Name: resources_languageid_idx; Type: INDEX; Schema: web; Owner: -
--

CREATE INDEX resources_languageid_idx ON web.resources USING btree (languageid) INCLUDE (languageid);


--
-- Name: resources_webserviceid_idx; Type: INDEX; Schema: web; Owner: -
--

CREATE INDEX resources_webserviceid_idx ON web.resources USING btree (websiteid) INCLUDE (websiteid);


--
-- Name: resourceconnections child_fk; Type: FK CONSTRAINT; Schema: web; Owner: -
--

ALTER TABLE ONLY web.resourceconnections
    ADD CONSTRAINT child_fk FOREIGN KEY (child) REFERENCES web.resources(resourceid) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: resources contenttypes_fk; Type: FK CONSTRAINT; Schema: web; Owner: -
--

ALTER TABLE ONLY web.resources
    ADD CONSTRAINT contenttypes_fk FOREIGN KEY (contenttype) REFERENCES web.contenttypes(contenttypeid) MATCH FULL;


--
-- Name: resources creator_fk; Type: FK CONSTRAINT; Schema: web; Owner: -
--

ALTER TABLE ONLY web.resources
    ADD CONSTRAINT creator_fk FOREIGN KEY (creator) REFERENCES account.users(userid) MATCH FULL;


--
-- Name: metavalues languageid_fk; Type: FK CONSTRAINT; Schema: web; Owner: -
--

ALTER TABLE ONLY web.metavalues
    ADD CONSTRAINT languageid_fk FOREIGN KEY (languageid) REFERENCES public.languages(languageid);


--
-- Name: menuitemtitles languages_fk; Type: FK CONSTRAINT; Schema: web; Owner: -
--

ALTER TABLE ONLY web.menuitemtitles
    ADD CONSTRAINT languages_fk FOREIGN KEY (languageid) REFERENCES public.languages(languageid) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: resources languages_fk; Type: FK CONSTRAINT; Schema: web; Owner: -
--

ALTER TABLE ONLY web.resources
    ADD CONSTRAINT languages_fk FOREIGN KEY (languageid) REFERENCES public.languages(languageid) MATCH FULL ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: menuitemtitles menuitems_fk; Type: FK CONSTRAINT; Schema: web; Owner: -
--

ALTER TABLE ONLY web.menuitemtitles
    ADD CONSTRAINT menuitems_fk FOREIGN KEY (menuitemid) REFERENCES web.menuitems(menuitemid) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: menuitems menus_fk; Type: FK CONSTRAINT; Schema: web; Owner: -
--

ALTER TABLE ONLY web.menuitems
    ADD CONSTRAINT menus_fk FOREIGN KEY (menuid) REFERENCES web.menus(menuid) MATCH FULL ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: menus menus_webserviceid_fk; Type: FK CONSTRAINT; Schema: web; Owner: -
--

ALTER TABLE ONLY web.menus
    ADD CONSTRAINT menus_webserviceid_fk FOREIGN KEY (websiteid) REFERENCES website.websites(websiteid) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: menus menus_websiteid_fk; Type: FK CONSTRAINT; Schema: web; Owner: -
--

ALTER TABLE ONLY web.menus
    ADD CONSTRAINT menus_websiteid_fk FOREIGN KEY (websiteid) REFERENCES website.websites(websiteid) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: metavalues metakeyid_fk; Type: FK CONSTRAINT; Schema: web; Owner: -
--

ALTER TABLE ONLY web.metavalues
    ADD CONSTRAINT metakeyid_fk FOREIGN KEY (metakeyid) REFERENCES web.metakeys(metakeyid) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: metaconnections metavalueid_fk; Type: FK CONSTRAINT; Schema: web; Owner: -
--

ALTER TABLE ONLY web.metaconnections
    ADD CONSTRAINT metavalueid_fk FOREIGN KEY (metavalueid) REFERENCES web.metavalues(metavalueid) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: resources owner_fk; Type: FK CONSTRAINT; Schema: web; Owner: -
--

ALTER TABLE ONLY web.resources
    ADD CONSTRAINT owner_fk FOREIGN KEY (owner) REFERENCES account.users(userid) MATCH FULL;


--
-- Name: comments parent_fk; Type: FK CONSTRAINT; Schema: web; Owner: -
--

ALTER TABLE ONLY web.comments
    ADD CONSTRAINT parent_fk FOREIGN KEY (parentid) REFERENCES web.comments(commentid) MATCH FULL;


--
-- Name: menuitems parent_fk; Type: FK CONSTRAINT; Schema: web; Owner: -
--

ALTER TABLE ONLY web.menuitems
    ADD CONSTRAINT parent_fk FOREIGN KEY (parentid) REFERENCES web.menuitems(menuitemid) MATCH FULL ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: resourceconnections parent_fk; Type: FK CONSTRAINT; Schema: web; Owner: -
--

ALTER TABLE ONLY web.resourceconnections
    ADD CONSTRAINT parent_fk FOREIGN KEY (parent) REFERENCES web.resources(resourceid) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: resources publisher_fk; Type: FK CONSTRAINT; Schema: web; Owner: -
--

ALTER TABLE ONLY web.resources
    ADD CONSTRAINT publisher_fk FOREIGN KEY (publisher) REFERENCES account.users(userid) MATCH FULL;


--
-- Name: resources resourcealias_fk; Type: FK CONSTRAINT; Schema: web; Owner: -
--

ALTER TABLE ONLY web.resources
    ADD CONSTRAINT resourcealias_fk FOREIGN KEY (resourcealias) REFERENCES web.resources(resourceid) MATCH FULL;


--
-- Name: metaconnections resourceid_fk; Type: FK CONSTRAINT; Schema: web; Owner: -
--

ALTER TABLE ONLY web.metaconnections
    ADD CONSTRAINT resourceid_fk FOREIGN KEY (resourceid) REFERENCES web.resources(resourceid) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: comments resources_fk; Type: FK CONSTRAINT; Schema: web; Owner: -
--

ALTER TABLE ONLY web.comments
    ADD CONSTRAINT resources_fk FOREIGN KEY (resourceid) REFERENCES web.resources(resourceid) MATCH FULL ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: uris resources_fk; Type: FK CONSTRAINT; Schema: web; Owner: -
--

ALTER TABLE ONLY web.uris
    ADD CONSTRAINT resources_fk FOREIGN KEY (resourceid) REFERENCES web.resources(resourceid) MATCH FULL ON UPDATE CASCADE ON DELETE SET NULL;


--
-- Name: resources resources_webserviceid_fk; Type: FK CONSTRAINT; Schema: web; Owner: -
--

ALTER TABLE ONLY web.resources
    ADD CONSTRAINT resources_webserviceid_fk FOREIGN KEY (websiteid) REFERENCES website.websites(websiteid) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: resources resources_websiteid_fk; Type: FK CONSTRAINT; Schema: web; Owner: -
--

ALTER TABLE ONLY web.resources
    ADD CONSTRAINT resources_websiteid_fk FOREIGN KEY (websiteid) REFERENCES website.websites(websiteid) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: resources templates_fk; Type: FK CONSTRAINT; Schema: web; Owner: -
--

ALTER TABLE ONLY web.resources
    ADD CONSTRAINT templates_fk FOREIGN KEY (templateid) REFERENCES web.templates(templateid) MATCH FULL ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- Name: menuitems uris_fk; Type: FK CONSTRAINT; Schema: web; Owner: -
--

ALTER TABLE ONLY web.menuitems
    ADD CONSTRAINT uris_fk FOREIGN KEY (uriid) REFERENCES web.uris(uriid) MATCH FULL ON UPDATE CASCADE ON DELETE SET NULL;


--
-- Name: homes users_fk; Type: FK CONSTRAINT; Schema: web; Owner: -
--

ALTER TABLE ONLY web.homes
    ADD CONSTRAINT users_fk FOREIGN KEY (homeid) REFERENCES account.users(userid) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--
