--
-- PostgreSQL database dump
--


-- Dumped from database version 16.14 (Ubuntu 16.14-0ubuntu0.24.04.1)
-- Dumped by pg_dump version 16.14 (Ubuntu 16.14-0ubuntu0.24.04.1)


--
-- Name: stats; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA IF NOT EXISTS stats;




--
-- Name: counters; Type: TABLE; Schema: stats; Owner: -
--

CREATE TABLE stats.counters (
    counterid bigint NOT NULL
);


--
-- Name: counters_counterid_seq; Type: SEQUENCE; Schema: stats; Owner: -
--

ALTER TABLE stats.counters ALTER COLUMN counterid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME stats.counters_counterid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: referrers; Type: TABLE; Schema: stats; Owner: -
--

CREATE TABLE stats.referrers (
    referrerid bigint NOT NULL
);


--
-- Name: referrers_referrerid_seq; Type: SEQUENCE; Schema: stats; Owner: -
--

ALTER TABLE stats.referrers ALTER COLUMN referrerid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME stats.referrers_referrerid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: visitcaches; Type: TABLE; Schema: stats; Owner: -
--

CREATE TABLE stats.visitcaches (
    visitcacheid integer NOT NULL
);


--
-- Name: visitcaches_visitcacheid_seq; Type: SEQUENCE; Schema: stats; Owner: -
--

ALTER TABLE stats.visitcaches ALTER COLUMN visitcacheid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME stats.visitcaches_visitcacheid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: counters counters_pk; Type: CONSTRAINT; Schema: stats; Owner: -
--

ALTER TABLE ONLY stats.counters
    ADD CONSTRAINT counters_pk PRIMARY KEY (counterid);


--
-- Name: referrers referrers_pk; Type: CONSTRAINT; Schema: stats; Owner: -
--

ALTER TABLE ONLY stats.referrers
    ADD CONSTRAINT referrers_pk PRIMARY KEY (referrerid);


--
-- Name: visitcaches visitcaches_pk; Type: CONSTRAINT; Schema: stats; Owner: -
--

ALTER TABLE ONLY stats.visitcaches
    ADD CONSTRAINT visitcaches_pk PRIMARY KEY (visitcacheid);


--
-- PostgreSQL database dump complete
--
