--
-- PostgreSQL database dump
--


-- Dumped from database version 16.14 (Ubuntu 16.14-0ubuntu0.24.04.1)
-- Dumped by pg_dump version 16.14 (Ubuntu 16.14-0ubuntu0.24.04.1)


--
-- Name: account; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA IF NOT EXISTS account;




--
-- Name: contacts; Type: TABLE; Schema: account; Owner: -
--

CREATE TABLE account.contacts (
    contactid bigint NOT NULL,
    email character varying NOT NULL,
    givenname character varying,
    commonname character varying,
    displayname character varying DEFAULT ''::character varying NOT NULL,
    organization character varying,
    address character varying,
    pc character varying,
    city character varying(63),
    telephone character varying(31),
    mobile character varying(31),
    website character varying,
    dob date,
    countryid integer,
    languageid integer DEFAULT 1,
    stateid integer,
    lastcheck timestamp without time zone
);


--
-- Name: COLUMN contacts.lastcheck; Type: COMMENT; Schema: account; Owner: -
--

COMMENT ON COLUMN account.contacts.lastcheck IS 'Last verification of contact details';


--
-- Name: contacts_contactid_seq; Type: SEQUENCE; Schema: account; Owner: -
--

ALTER TABLE account.contacts ALTER COLUMN contactid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME account.contacts_contactid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: displayfields; Type: TABLE; Schema: account; Owner: -
--

CREATE TABLE account.displayfields (
    displayfieldid bigint NOT NULL,
    fieldnames character varying[] NOT NULL,
    displaylevel smallint DEFAULT 0 NOT NULL,
    userid bigint NOT NULL
);


--
-- Name: displayfields_displayfieldid_seq; Type: SEQUENCE; Schema: account; Owner: -
--

ALTER TABLE account.displayfields ALTER COLUMN displayfieldid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME account.displayfields_displayfieldid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: emailconfirmationrequests; Type: TABLE; Schema: account; Owner: -
--

CREATE TABLE account.emailconfirmationrequests (
    requestid bigint NOT NULL,
    newemail character varying NOT NULL,
    ip inet,
    requesttime timestamp with time zone DEFAULT now() NOT NULL,
    confirmationuuid uuid DEFAULT gen_random_uuid() NOT NULL,
    contactid bigint NOT NULL,
    userid bigint NOT NULL
);


--
-- Name: emailconfirmationrequests_requestid_seq; Type: SEQUENCE; Schema: account; Owner: -
--

ALTER TABLE account.emailconfirmationrequests ALTER COLUMN requestid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME account.emailconfirmationrequests_requestid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: groups; Type: TABLE; Schema: account; Owner: -
--

CREATE TABLE account.groups (
    groupid bigint NOT NULL,
    groupname character varying NOT NULL,
    creator integer,
    updater integer
);


--
-- Name: groups_groupid_seq; Type: SEQUENCE; Schema: account; Owner: -
--

ALTER TABLE account.groups ALTER COLUMN groupid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME account.groups_groupid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: images; Type: TABLE; Schema: account; Owner: -
--

CREATE TABLE account.images (
    imageid bigint NOT NULL,
    profileimage bit varying NOT NULL,
    userid bigint NOT NULL,
    filename character varying
);


--
-- Name: images_imageid_seq; Type: SEQUENCE; Schema: account; Owner: -
--

ALTER TABLE account.images ALTER COLUMN imageid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME account.images_imageid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: loginfailures; Type: TABLE; Schema: account; Owner: -
--

CREATE TABLE account.loginfailures (
    loginfailureid bigint NOT NULL,
    ip inet NOT NULL,
    username character varying(31) DEFAULT ''::character varying NOT NULL,
    failuretime timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: loginfailures_loginfailureid_seq; Type: SEQUENCE; Schema: account; Owner: -
--

ALTER TABLE account.loginfailures ALTER COLUMN loginfailureid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME account.loginfailures_loginfailureid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: logins; Type: TABLE; Schema: account; Owner: -
--

CREATE TABLE account.logins (
    loginid bigint NOT NULL,
    userid bigint NOT NULL,
    logintime timestamp with time zone DEFAULT now() NOT NULL,
    active boolean DEFAULT true NOT NULL,
    ip inet NOT NULL
);


--
-- Name: logins_loginid_seq; Type: SEQUENCE; Schema: account; Owner: -
--

ALTER TABLE account.logins ALTER COLUMN loginid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME account.logins_loginid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: messages; Type: TABLE; Schema: account; Owner: -
--

CREATE TABLE account.messages (
    messageid bigint NOT NULL,
    recipientid bigint NOT NULL,
    senderid bigint,
    contents json NOT NULL,
    viewed boolean DEFAULT false NOT NULL,
    created timestamp with time zone DEFAULT now(),
    modified timestamp with time zone
);


--
-- Name: messages_messageid_seq; Type: SEQUENCE; Schema: account; Owner: -
--

ALTER TABLE account.messages ALTER COLUMN messageid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME account.messages_messageid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: passwords; Type: TABLE; Schema: account; Owner: -
--

CREATE TABLE account.passwords (
    passwordid bigint NOT NULL,
    passwordmysql character varying,
    passwordsha512 character varying,
    passwordpbkdf2 character varying,
    passwordbcrypt character varying,
    passwordargon2id character varying,
    changed timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: passwords_passwordid_seq; Type: SEQUENCE; Schema: account; Owner: -
--

ALTER TABLE account.passwords ALTER COLUMN passwordid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME account.passwords_passwordid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: permissionnames; Type: TABLE; Schema: account; Owner: -
--

CREATE TABLE account.permissionnames (
    permissionnameid integer NOT NULL,
    permissionid integer NOT NULL,
    languageid integer NOT NULL,
    permissionname character varying(191) NOT NULL
);


--
-- Name: permissionnames_permissionnameid_seq; Type: SEQUENCE; Schema: account; Owner: -
--

ALTER TABLE account.permissionnames ALTER COLUMN permissionnameid ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME account.permissionnames_permissionnameid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: permissions; Type: TABLE; Schema: account; Owner: -
--

CREATE TABLE account.permissions (
    permissionid integer NOT NULL
);


--
-- Name: permissions_permissionid_seq; Type: SEQUENCE; Schema: account; Owner: -
--

ALTER TABLE account.permissions ALTER COLUMN permissionid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME account.permissions_permissionid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: presentations; Type: TABLE; Schema: account; Owner: -
--

CREATE TABLE account.presentations (
    presentationid bigint NOT NULL,
    presentation text DEFAULT ''::text NOT NULL,
    userid bigint NOT NULL,
    languageid integer DEFAULT 1 NOT NULL
);


--
-- Name: presentations_presentationid_seq; Type: SEQUENCE; Schema: account; Owner: -
--

ALTER TABLE account.presentations ALTER COLUMN presentationid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME account.presentations_presentationid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: rolenames; Type: TABLE; Schema: account; Owner: -
--

CREATE TABLE account.rolenames (
    rolenameid integer NOT NULL,
    rolename character varying(191) NOT NULL,
    languageid integer NOT NULL,
    roleid integer NOT NULL
);


--
-- Name: rolenames_rolenameid_seq; Type: SEQUENCE; Schema: account; Owner: -
--

ALTER TABLE account.rolenames ALTER COLUMN rolenameid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME account.rolenames_rolenameid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: rolepermissions; Type: TABLE; Schema: account; Owner: -
--

CREATE TABLE account.rolepermissions (
    rolepermissionid integer NOT NULL,
    roleid integer NOT NULL,
    permissionid integer
);


--
-- Name: rolepermissions_rolepermissionid_seq; Type: SEQUENCE; Schema: account; Owner: -
--

ALTER TABLE account.rolepermissions ALTER COLUMN rolepermissionid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME account.rolepermissions_rolepermissionid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: roles; Type: TABLE; Schema: account; Owner: -
--

CREATE TABLE account.roles (
    roleid integer NOT NULL
);


--
-- Name: roles_roleid_seq; Type: SEQUENCE; Schema: account; Owner: -
--

ALTER TABLE account.roles ALTER COLUMN roleid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME account.roles_roleid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: userbans; Type: TABLE; Schema: account; Owner: -
--

CREATE TABLE account.userbans (
    userbanid bigint NOT NULL,
    banner bigint NOT NULL,
    banned bigint NOT NULL
);


--
-- Name: userbans_userbanid_seq; Type: SEQUENCE; Schema: account; Owner: -
--

ALTER TABLE account.userbans ALTER COLUMN userbanid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME account.userbans_userbanid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: usergroups; Type: TABLE; Schema: account; Owner: -
--

CREATE TABLE account.usergroups (
    usergroupid bigint NOT NULL,
    userid bigint NOT NULL,
    groupid bigint NOT NULL
);


--
-- Name: usergroups_usergroupid_seq; Type: SEQUENCE; Schema: account; Owner: -
--

ALTER TABLE account.usergroups ALTER COLUMN usergroupid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME account.usergroups_usergroupid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: account; Owner: -
--

CREATE TABLE account.users (
    userid bigint NOT NULL,
    username character varying(31) NOT NULL,
    deleted boolean DEFAULT false NOT NULL,
    blocked boolean DEFAULT false NOT NULL,
    activated boolean DEFAULT false NOT NULL,
    created timestamp with time zone DEFAULT now(),
    modified timestamp with time zone,
    checked boolean DEFAULT false NOT NULL,
    contactid bigint NOT NULL,
    useruuid uuid DEFAULT gen_random_uuid() NOT NULL,
    passwordid bigint
);


--
-- Name: users_userid_seq; Type: SEQUENCE; Schema: account; Owner: -
--

ALTER TABLE account.users ALTER COLUMN userid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME account.users_userid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users contactid_uq; Type: CONSTRAINT; Schema: account; Owner: -
--

ALTER TABLE ONLY account.users
    ADD CONSTRAINT contactid_uq UNIQUE (contactid);


--
-- Name: contacts contacts_pk; Type: CONSTRAINT; Schema: account; Owner: -
--

ALTER TABLE ONLY account.contacts
    ADD CONSTRAINT contacts_pk PRIMARY KEY (contactid);


--
-- Name: displayfields displayfields_pk; Type: CONSTRAINT; Schema: account; Owner: -
--

ALTER TABLE ONLY account.displayfields
    ADD CONSTRAINT displayfields_pk PRIMARY KEY (displayfieldid);


--
-- Name: emailconfirmationrequests emailconfirmationrequests_pk; Type: CONSTRAINT; Schema: account; Owner: -
--

ALTER TABLE ONLY account.emailconfirmationrequests
    ADD CONSTRAINT emailconfirmationrequests_pk PRIMARY KEY (requestid);


--
-- Name: groups groupname_uq; Type: CONSTRAINT; Schema: account; Owner: -
--

ALTER TABLE ONLY account.groups
    ADD CONSTRAINT groupname_uq UNIQUE (groupname);


--
-- Name: groups groups_pk; Type: CONSTRAINT; Schema: account; Owner: -
--

ALTER TABLE ONLY account.groups
    ADD CONSTRAINT groups_pk PRIMARY KEY (groupid);


--
-- Name: images images_pk; Type: CONSTRAINT; Schema: account; Owner: -
--

ALTER TABLE ONLY account.images
    ADD CONSTRAINT images_pk PRIMARY KEY (imageid);


--
-- Name: loginfailures loginfailures_pk; Type: CONSTRAINT; Schema: account; Owner: -
--

ALTER TABLE ONLY account.loginfailures
    ADD CONSTRAINT loginfailures_pk PRIMARY KEY (loginfailureid);


--
-- Name: logins logins_pk; Type: CONSTRAINT; Schema: account; Owner: -
--

ALTER TABLE ONLY account.logins
    ADD CONSTRAINT logins_pk PRIMARY KEY (loginid);


--
-- Name: messages messages_pk; Type: CONSTRAINT; Schema: account; Owner: -
--

ALTER TABLE ONLY account.messages
    ADD CONSTRAINT messages_pk PRIMARY KEY (messageid);


--
-- Name: passwords passwords_pk; Type: CONSTRAINT; Schema: account; Owner: -
--

ALTER TABLE ONLY account.passwords
    ADD CONSTRAINT passwords_pk PRIMARY KEY (passwordid);


--
-- Name: permissionnames permissionnames_pk; Type: CONSTRAINT; Schema: account; Owner: -
--

ALTER TABLE ONLY account.permissionnames
    ADD CONSTRAINT permissionnames_pk PRIMARY KEY (permissionnameid);


--
-- Name: permissions permissions_pk; Type: CONSTRAINT; Schema: account; Owner: -
--

ALTER TABLE ONLY account.permissions
    ADD CONSTRAINT permissions_pk PRIMARY KEY (permissionid);


--
-- Name: presentations presentations_pk; Type: CONSTRAINT; Schema: account; Owner: -
--

ALTER TABLE ONLY account.presentations
    ADD CONSTRAINT presentations_pk PRIMARY KEY (presentationid);


--
-- Name: rolenames rolenames_pk; Type: CONSTRAINT; Schema: account; Owner: -
--

ALTER TABLE ONLY account.rolenames
    ADD CONSTRAINT rolenames_pk PRIMARY KEY (rolenameid);


--
-- Name: rolepermissions rolepermissions_pk; Type: CONSTRAINT; Schema: account; Owner: -
--

ALTER TABLE ONLY account.rolepermissions
    ADD CONSTRAINT rolepermissions_pk PRIMARY KEY (rolepermissionid);


--
-- Name: roles roles_pk; Type: CONSTRAINT; Schema: account; Owner: -
--

ALTER TABLE ONLY account.roles
    ADD CONSTRAINT roles_pk PRIMARY KEY (roleid);


--
-- Name: userbans userbans_pk; Type: CONSTRAINT; Schema: account; Owner: -
--

ALTER TABLE ONLY account.userbans
    ADD CONSTRAINT userbans_pk PRIMARY KEY (userbanid);


--
-- Name: usergroups usergroups_pk; Type: CONSTRAINT; Schema: account; Owner: -
--

ALTER TABLE ONLY account.usergroups
    ADD CONSTRAINT usergroups_pk PRIMARY KEY (usergroupid);


--
-- Name: images userid_uq; Type: CONSTRAINT; Schema: account; Owner: -
--

ALTER TABLE ONLY account.images
    ADD CONSTRAINT userid_uq UNIQUE (userid);


--
-- Name: users username_uq; Type: CONSTRAINT; Schema: account; Owner: -
--

ALTER TABLE ONLY account.users
    ADD CONSTRAINT username_uq UNIQUE (username);


--
-- Name: users users_pk; Type: CONSTRAINT; Schema: account; Owner: -
--

ALTER TABLE ONLY account.users
    ADD CONSTRAINT users_pk PRIMARY KEY (userid);


--
-- Name: loginfailures_ip_idx; Type: INDEX; Schema: account; Owner: -
--

CREATE INDEX loginfailures_ip_idx ON account.loginfailures USING btree (ip) INCLUDE (ip) WITH (fillfactor='90');


--
-- Name: logins_userid_idx; Type: INDEX; Schema: account; Owner: -
--

CREATE INDEX logins_userid_idx ON account.logins USING btree (userid DESC NULLS LAST) INCLUDE (userid);


--
-- Name: messages_recipientid_idx; Type: INDEX; Schema: account; Owner: -
--

CREATE INDEX messages_recipientid_idx ON account.messages USING btree (recipientid);


--
-- Name: userbans banned_id; Type: FK CONSTRAINT; Schema: account; Owner: -
--

ALTER TABLE ONLY account.userbans
    ADD CONSTRAINT banned_id FOREIGN KEY (banned) REFERENCES account.users(userid) MATCH FULL ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: userbans banner_id; Type: FK CONSTRAINT; Schema: account; Owner: -
--

ALTER TABLE ONLY account.userbans
    ADD CONSTRAINT banner_id FOREIGN KEY (banner) REFERENCES account.users(userid) MATCH FULL ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: users contacts_fk; Type: FK CONSTRAINT; Schema: account; Owner: -
--

ALTER TABLE ONLY account.users
    ADD CONSTRAINT contacts_fk FOREIGN KEY (contactid) REFERENCES account.contacts(contactid) MATCH FULL ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: contacts countries_fk; Type: FK CONSTRAINT; Schema: account; Owner: -
--

ALTER TABLE ONLY account.contacts
    ADD CONSTRAINT countries_fk FOREIGN KEY (countryid) REFERENCES public.countries(countryid) MATCH FULL ON UPDATE CASCADE ON DELETE SET NULL;


--
-- Name: groups creator_fk; Type: FK CONSTRAINT; Schema: account; Owner: -
--

ALTER TABLE ONLY account.groups
    ADD CONSTRAINT creator_fk FOREIGN KEY (creator) REFERENCES account.users(userid) MATCH FULL ON DELETE SET NULL;


--
-- Name: usergroups groups_fk; Type: FK CONSTRAINT; Schema: account; Owner: -
--

ALTER TABLE ONLY account.usergroups
    ADD CONSTRAINT groups_fk FOREIGN KEY (groupid) REFERENCES account.groups(groupid) MATCH FULL ON DELETE CASCADE;


--
-- Name: contacts languages_fk; Type: FK CONSTRAINT; Schema: account; Owner: -
--

ALTER TABLE ONLY account.contacts
    ADD CONSTRAINT languages_fk FOREIGN KEY (languageid) REFERENCES public.languages(languageid) MATCH FULL ON UPDATE CASCADE ON DELETE SET NULL;


--
-- Name: permissionnames languages_fk; Type: FK CONSTRAINT; Schema: account; Owner: -
--

ALTER TABLE ONLY account.permissionnames
    ADD CONSTRAINT languages_fk FOREIGN KEY (languageid) REFERENCES public.languages(languageid) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: presentations languages_fk; Type: FK CONSTRAINT; Schema: account; Owner: -
--

ALTER TABLE ONLY account.presentations
    ADD CONSTRAINT languages_fk FOREIGN KEY (languageid) REFERENCES public.languages(languageid) MATCH FULL ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: rolenames languages_fk; Type: FK CONSTRAINT; Schema: account; Owner: -
--

ALTER TABLE ONLY account.rolenames
    ADD CONSTRAINT languages_fk FOREIGN KEY (languageid) REFERENCES public.languages(languageid) MATCH FULL ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: permissionnames permissions_fk; Type: FK CONSTRAINT; Schema: account; Owner: -
--

ALTER TABLE ONLY account.permissionnames
    ADD CONSTRAINT permissions_fk FOREIGN KEY (permissionid) REFERENCES account.permissions(permissionid) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: rolepermissions permissions_fk; Type: FK CONSTRAINT; Schema: account; Owner: -
--

ALTER TABLE ONLY account.rolepermissions
    ADD CONSTRAINT permissions_fk FOREIGN KEY (permissionid) REFERENCES account.permissions(permissionid) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: messages recipient_fk; Type: FK CONSTRAINT; Schema: account; Owner: -
--

ALTER TABLE ONLY account.messages
    ADD CONSTRAINT recipient_fk FOREIGN KEY (recipientid) REFERENCES account.users(userid) MATCH FULL ON DELETE CASCADE;


--
-- Name: rolenames roles_fk; Type: FK CONSTRAINT; Schema: account; Owner: -
--

ALTER TABLE ONLY account.rolenames
    ADD CONSTRAINT roles_fk FOREIGN KEY (roleid) REFERENCES account.roles(roleid) MATCH FULL ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: rolepermissions roles_fk; Type: FK CONSTRAINT; Schema: account; Owner: -
--

ALTER TABLE ONLY account.rolepermissions
    ADD CONSTRAINT roles_fk FOREIGN KEY (roleid) REFERENCES account.roles(roleid) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: messages sender_fk; Type: FK CONSTRAINT; Schema: account; Owner: -
--

ALTER TABLE ONLY account.messages
    ADD CONSTRAINT sender_fk FOREIGN KEY (senderid) REFERENCES account.users(userid) MATCH FULL;


--
-- Name: contacts states_fk; Type: FK CONSTRAINT; Schema: account; Owner: -
--

ALTER TABLE ONLY account.contacts
    ADD CONSTRAINT states_fk FOREIGN KEY (stateid) REFERENCES public.states(stateid) ON UPDATE CASCADE ON DELETE SET NULL;


--
-- Name: groups updater_fk; Type: FK CONSTRAINT; Schema: account; Owner: -
--

ALTER TABLE ONLY account.groups
    ADD CONSTRAINT updater_fk FOREIGN KEY (updater) REFERENCES account.users(userid) MATCH FULL ON DELETE SET NULL;


--
-- Name: displayfields users_fk; Type: FK CONSTRAINT; Schema: account; Owner: -
--

ALTER TABLE ONLY account.displayfields
    ADD CONSTRAINT users_fk FOREIGN KEY (userid) REFERENCES account.users(userid) MATCH FULL ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: emailconfirmationrequests users_fk; Type: FK CONSTRAINT; Schema: account; Owner: -
--

ALTER TABLE ONLY account.emailconfirmationrequests
    ADD CONSTRAINT users_fk FOREIGN KEY (userid) REFERENCES account.users(userid) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: images users_fk; Type: FK CONSTRAINT; Schema: account; Owner: -
--

ALTER TABLE ONLY account.images
    ADD CONSTRAINT users_fk FOREIGN KEY (userid) REFERENCES account.users(userid) MATCH FULL ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: logins users_fk; Type: FK CONSTRAINT; Schema: account; Owner: -
--

ALTER TABLE ONLY account.logins
    ADD CONSTRAINT users_fk FOREIGN KEY (userid) REFERENCES account.users(userid) MATCH FULL ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: presentations users_fk; Type: FK CONSTRAINT; Schema: account; Owner: -
--

ALTER TABLE ONLY account.presentations
    ADD CONSTRAINT users_fk FOREIGN KEY (userid) REFERENCES account.users(userid) MATCH FULL ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: usergroups users_fk; Type: FK CONSTRAINT; Schema: account; Owner: -
--

ALTER TABLE ONLY account.usergroups
    ADD CONSTRAINT users_fk FOREIGN KEY (userid) REFERENCES account.users(userid) MATCH FULL ON DELETE CASCADE;


--
-- Name: users users_passwordid_fk; Type: FK CONSTRAINT; Schema: account; Owner: -
--

ALTER TABLE ONLY account.users
    ADD CONSTRAINT users_passwordid_fk FOREIGN KEY (passwordid) REFERENCES account.passwords(passwordid) ON UPDATE CASCADE ON DELETE SET NULL;


--
-- PostgreSQL database dump complete
--
